cilium/proxy

- WORKSPACE
Update Envoy to release 1.17.1.
> envoy: Update to 1.17.1

- cilium/accesslog.cc
Add response headers to response access log messages in addition to keeping the request headers.
> accesslog: Add response headers to response access log messages.

- README.md
Signed-off-by: Raphaël Pinson <raphael@isovalent.com>
> docs(README): fix small typo

- WORKSPACE
> build: fix comment

- cilium/l7policy.cc
Since we removed request headers from response logs we have missed logging the request headers for failed requests, while it would be useful to see exactly what was denied or what kind of a request failed.
Change to always log requests. A request will be logged as denied if a local 403 response for it was generated. This happens  for policy denies and in some misconfiguration cases (where the upstream callback returns `false`). For any other local failures (such as 503s, etc.) the request will be logged but not as "denied". The following response log will contain the status code in all cases.
This is more logical as it is the request that gets denied, not the response. [Cilium already maps denied logs to request type](https://github.com/cilium/cilium/blob/v1.12/pkg/envoy/accesslog.go#L56-L …
> l7policy: Log requests also when not allowed, or connection fails.

- cilium/tls_wrapper.cc
Make Cilium TLS wrapper more generic by defaulting to a raw buffer (i.e., non-TLS) socket when there is no TLS context for the connection in the policy. This allows the same (TLS) cluster to be shared with TLS and non-TLS traffic, as directed via the network policy.
> tls: Default to a raw socket

- .github/workflows/build.yaml
- .github/workflows/cache-build.yaml
- .github/workflows/test.yaml
Don't bother using swap with the big runners.
> gh: Runners to the max

- .github/workflows/build-envoy-images-release.yaml
- .github/workflows/ci-tests.yaml
> gha: Correct workflow configuration

- .github/workflows/build-envoy-image-ci.yaml
- .github/workflows/build-envoy-images-release.yaml
- .github/workflows/ci-tests.yaml
- Dockerfile
- Dockerfile.tests
- Makefile.docker
- README.md
Relates: https://github.com/cilium/proxy/pull/121#discussion_r1108233827
Testing was done with temp commit, I will remove the temp commit after review is done.
[Build PR](https://github.com/cilium/proxy/actions/runs/4203181839/jobs/7292259976)
[Integration Test](https://github.com/cilium/proxy/actions/runs/4203181838/jobs/7292259957)
> chore: Rename BUILDER_IMAGE to ARCHIVE_IMAGE

- .github/workflows/build-envoy-images-release.yaml
- .github/workflows/cilium-integration-tests.yaml
- Makefile.docker
- README.md
Fixes: https://github.com/cilium/proxy/issues/158
> Rename main branch to main

- envoy_build_config/extensions_build_config.bzl
This PR includes forward ports of these two commits that are in the v1.23 branch:
- sync envoy build config (commit 558b779aefaa336dcd19e68db9ccb7a111b3c2c2)
- enable internal listener extensions (commit 38450b2108d4c5206b86bcdf8218df6208adb895)
These are already in the main and v1.25 branches.
> Internal listener v1.24

- WORKSPACE
https://github.com/envoyproxy/envoy/releases/tag/v1.23.12
> envoy: Bump to v1.23.12

- Dockerfile.builder
- Dockerfile.tests
Add libcap-dev needed for capability drop support.
> builder: Add libcap-dev

- .github/workflows/build-envoy-image-ci.yaml
Fix the ref in the shown digest is missing the `builder` part.
> github: Fix shown digest ref

- envoy.bazelrc
Sync changes in Envoy's .bazelrc to our envoy.bazelrc.
Fixes: #324
> envoy: Sync envoy.bazelrc

- Dockerfile
Fixes: https://github.com/cilium/proxy/issues/308
> docker: Use envoy builder image as proxylib builder

- .github/renovate.json5
- Dockerfile.builder
> v1.26 Backports 2023-12-06

- envoy_build_config/extensions_build_config.bzl
> support envoy.http.stateful_header_formatters.preserve_case

- envoy_build_config/extensions_build_config.bzl
Relates: https://github.com/cilium/cilium/issues/30180
> build: Enable proxy_protocol filter

- envoy_build_config/extensions_build_config.bzl
> v1.27 Backports 2024-01-16

- cilium/socket_option.h
Manual backport of https://github.com/cilium/proxy/pull/505
Currently, the socket option `SO_REUSEPORT` is always set on all sockets - including the listener socket itself.
This doesn't take into account, that the Cilium Agent disables port reuse on the listener socket via Envoy listener configuration (`enable_reuse_port=false`) if BPF TPROXY is enabled.
In these cases, the cilium socket options
overrule and set the socket option `SO_REUSEPORT` - regardless of what's configured via Envoy listener API.. This leads to issues with BPF TPROXY (socket lookup fails).
Therefore, this commit changes the logic that the socket option `SO_REUSEPORT` is never set on the listener socket itself.
Note: The goal of #315 was to move privileged logic into the starter and remove the privileges from the …
> [v1.27] api: socket options shouldn't set SO_REUSEPORT on listener socket

- patches/0002-upstream-Add-callback-for-upstream-authorization.patch
> v1.27 Backports 2024-02-21

- cilium/bpf.cc
Currently, interaction with BPF maps via syscalls (open, lookup) might result in log messages of the following form, where the error detail is `success`:
```
[info][filter] [cilium/conntrack.cc:229] cilium.bpf_metadata: IPv4 conntrack map global lookup failed: Success
```
This is due to the fact that BPF maps are accessed in the starter process. Hence, the syscalls are also executed in this separate process and the variable `errno` is never set in the Envoy process where the log is written..
Therefore, this commit fixes the error propagation by setting the variable `errno` after retrieving the response from the privileged client doing the call to the starter process.
Fixes: #315
Related to: #470
> bpf: fix error propagation for bpf syscalls

- cilium/bpf.cc
Backport of https://github.com/cilium/proxy/pull/674
> [1.27] bpf: fix error propagation for bpf syscalls

- Makefile
/usr/lib/llvm-17 may exist while all the clang dependencies may not be installed. Remove the '/usr/lib/llvm-17' target, and install clang on the 'clang.bazelrc' target directly. After this clang is installed whenever clang.bazelrc is missing, or bazel/setup_clang.sh changes.
> make: Install clang without checking /usr/lib/llvm-17

- Makefile
- UPGRADE_ENVOY.md
Some learning as part of recent upgrade
> docs: Add envoy.bazelrc sync step in UPGRADE_ENVOY.md

- cilium/privileged_service_client.cc
- cilium/socket_option.h
- starter/main.cc
> v1.28 Backports 2024-05-01

- starter/main.cc
> [v1.28] starter: fix Envoy program and argument order

- .github/workflows/build-envoy-images-release.yaml
> v1.29 Backports 2024-08-14

- cilium/tls_wrapper.cc
[ upstream commit 0b6312420f26df40a5f17812a152d82f771c83b3 ]
> tls_wrapper: Do not use raw socket if no policy is found

- .github/workflows/build-envoy-image-ci.yaml
- .github/workflows/build-envoy-images-release.yaml
- .github/workflows/ci-check-format.yaml
- .github/workflows/ci-tests.yaml
Relates: https://github.com/cilium/proxy/pull/850
Testing was done with temp commit as per below
https://github.com/cilium/proxy/actions/runs/11115813692/job/30884932514?pr=951
https://github.com/cilium/proxy/actions/runs/11115813698/job/30884932458?pr=951
https://github.com/cilium/proxy/actions/runs/11115813695/job/30884932421?pr=951
https://github.com/cilium/proxy/actions/runs/11115813689/job/30884932353?pr=951
https://github.com/cilium/proxy/actions/runs/11115813692/job/30884932735?pr=951
> bazel: Remove bazel version in docker tags

- .github/workflows/build-envoy-image-ci.yaml
- .github/workflows/build-envoy-images-release.yaml
- .github/workflows/ci-tests.yaml
Testing was done with temp commit (i.e. add pull_request instead of pull_request_target)
https://github.com/cilium/proxy/actions/runs/11336979723/job/31527828018?pr=970
https://github.com/cilium/proxy/actions/runs/11336979723/job/31527828296?pr=970
https://github.com/cilium/proxy/actions/runs/11336979720/job/31527828016?pr=970
> gha: Change to equinix runner

- cilium/network_policy.cc
When validating the input header value against a secret, it is advisable to use a timing-safe string comparison operator with a runtime independent of the number of equivalent prefix bytes of the secret and header value. This commit is to use CRYPTO_memcmp function[^1][^2] for string comparison, similar to what is done in envoy codebase.
[^1]: https://github.com/openssl/openssl/blob/master/doc/man3/CRYPTO_memcmp.pod
[^2]: https://github.com/openssl/openssl/blob/f4c467452694e1211395d17c2c027d99c35ee1e1/crypto/cpuid.c#L184
> policy: Use timing-safe string comparison

- envoy_build_config/extensions_build_config.bzl
> v1.29 Backports 2024-10-24

- cilium/network_policy.cc
Log on new stream on info level.
> policy: Log info on new stream

- cilium/BUILD
- cilium/accesslog.cc
- cilium/accesslog.h
- cilium/api/bpf_metadata.proto
- cilium/bpf_metadata.cc
- cilium/bpf_metadata.h
- cilium/health_check_sink.cc
- cilium/health_check_sink.h
- cilium/l7policy.cc
- cilium/l7policy.h
- cilium/network_filter.cc
- cilium/network_policy.cc
- cilium/network_policy.h
- cilium/socket_option.h
- cilium/tls_wrapper.cc
- cilium/tls_wrapper.h
- cilium/uds_client.cc
- cilium/uds_client.h
- cilium/websocket_config.cc
- tests/bpf_metadata.cc
- tests/cilium_http_integration_test.cc
- tests/cilium_http_upstream_integration_test.cc
- tests/cilium_network_policy_test.cc
- tests/health_check_sink_test.cc
```upstream-prs
992 988 995 1004
```
> v1.29 Backports 2024-11-12

- .github/renovate.json5
> renovate: Update version for main and v1.30 branch

- tests/cilium_network_policy_test.cc
Validate that overlapping port ranges apply logical OR of the rules for the overlapping ports.
> policy: Add test cases for HTTP policies with overlapping port ranges

- .github/workflows/cilium-integration-tests.yaml
- cilium/bpf_metadata.cc
- cilium/network_filter.cc
- cilium/network_policy.cc
- cilium/network_policy.h
- cilium/secret_watcher.cc
- cilium/socket_option.h
- cilium/tls_wrapper.cc
- tests/bpf_metadata.cc
- tests/metadata_config_test.cc
> Revert "[v1.30] Socket option no policy reference"

- cilium/network_policy.h
- cilium/secret_watcher.cc
Two more asserts changed to error logs.
> policy: Change remaining main thread asserts into error logs

- .github/renovate.json5
This was missed when the new branch is cut.
> renovate: Add v1.30 into base branch

- WORKSPACE
- cilium/network_policy.cc
- cilium/network_policy.h
- patches/0007-tcp_proxy-Check-for-nullptr-in-watermark-ASSERTs.patch
- patches/0008-thread_local-reset-slot-in-worker-threads-first.patch
> v1.31 Backports 2024-12-24

- bazel/toolchains/BUILD
- cilium/uds_client.cc
Fixes: https://github.com/cilium/proxy/pull/988
Fixes: https://github.com/cilium/proxy/issues/1056
> uds: fix thread safety issues

- .clangd
- .gitignore
- tools/gen_compilation_database.py
See the individual commits for more information
* build: add tools/gen_compilation_database.py
* clangd: add clangd configuration
Wait for dependent PR to be merged: https://github.com/cilium/proxy/pull/1086 (edit: :heavy_check_mark:)
> build: improve clangd LSP server support

- .clangd
- cilium/l7policy.cc
- cilium/network_filter.h
- cilium/privileged_service_client.cc
- cilium/tls_wrapper.cc
- cilium/websocket_codec.cc
- tests/health_check_sink_test.cc
See commits
Follow up of: https://github.com/cilium/proxy/pull/1100
> code: clangd related cleanups

- cilium/BUILD
Follow up of https://github.com/cilium/proxy/pull/1115 & https://github.com/cilium/proxy/pull/1116
> bazel: cleanup BUILD

- cilium/l7policy.cc
- cilium/network_filter.cc
> v1.31 Backports 2025-02-11

- .github/workflows/cilium-integration-tests.yaml
Relates: https://github.com/cilium/cilium/pull/37428
> gha: Sync up with the latest cilium/cilium changes

- .github/workflows/cilium-integration-tests.yaml
Also run ingress connectivity tests on each PR.
> ci: run ingress connectivity tests

- .github/workflows/build-envoy-image-ci.yaml
- .github/workflows/build-envoy-images-release.yaml
This is to fix the build failure in main https://github.com/cilium/proxy/actions/runs/13493679065/job/37696184564
Testing with the temp commit: https://github.com/cilium/proxy/actions/runs/13535118326/job/37825256706?pr=1187
> gha: Add Setup QEMU with QEMU 7.x

- .github/workflows/build-envoy-image-ci.yaml
- .github/workflows/build-envoy-images-release.yaml
> v1.31 Backports 2025-02-26

- cilium/bpf_metadata.cc
- cilium/bpf_metadata.h
- cilium/filter_state_cilium_policy.cc
- cilium/filter_state_cilium_policy.h
- cilium/l7policy.cc
- cilium/network_filter.cc
- cilium/network_policy.h
- tests/bpf_metadata.cc
- tests/metadata_config_test.cc
> v1.31 Backports 2025-03-05

- Makefile
> v1.31 Backports 2025-03-19

- cilium/tls_wrapper.cc
> v1.32 Backports 2025-04-16

- .github/workflows/cilium-integration-tests.yaml
Testing is done with the temp commit (i.e. change pull_request_target to pull_request)
https://github.com/cilium/proxy/actions/runs/14699082041/job/41245604029
> gha: Fix integration test workflow

- cilium/filter_state_cilium_policy.cc
> v1.32 Backports 2025-04-29

- .github/renovate.json5
- .github/workflows/renovate-config-validator.yaml
This was reverted by renovate in the below PR
https://github.com/cilium/proxy/pull/1325
> gha: Fix the renovate validation

- cilium/filter_state_cilium_policy.cc
Forgot to disable auto-merge, which then merged to main before waiting for the tests to succeed, resulting in a bad merge.
> main: Fix breakage due to auto merge

- .github/workflows/ci-clang-tidy.yaml
- Dockerfile
Add missing ARG TARGETARCH to Dockerfile.
> docker: Add missing ARG TARGETARCH

- cilium/BUILD
- cilium/bpf_metadata.cc
- cilium/bpf_metadata.h
- cilium/filter_state_cilium_destination.cc
- cilium/filter_state_cilium_destination.h
- cilium/network_filter.cc
- cilium/socket_option_source_address.cc
- cilium/socket_option_source_address.h
> v1.32 Backports 2025-05-16

- .github/workflows/build-envoy-image-ci.yaml
- .github/workflows/cilium-integration-tests.yaml
> v1.32 Backports 2025-05-23

- .github/workflows/codeql.yml
Setup CodeQL Slack Notifications.
> Setup CodeQL Slack notifications

- .github/workflows/cilium-integration-tests.yaml
- cilium/bpf_metadata.cc
- cilium/bpf_metadata.h
- cilium/filter_state_cilium_policy.cc
- cilium/filter_state_cilium_policy.h
- cilium/network_policy.cc
- cilium/network_policy.h
- cilium/secret_watcher.cc
- cilium/secret_watcher.h
- tests/bpf_metadata.cc
- tests/cilium_network_policy_test.cc
> v1.32 Backports 2025-06-04

- .github/workflows/ci-check-format.yaml
- .github/workflows/ci-clang-tidy.yaml
- .github/workflows/ci-tests.yaml
Please refer to individual commit for more details.
> gha: Move to pull request trigger

- .github/workflows/build-envoy-image-ci.yaml
- .github/workflows/cilium-gateway-api.yaml
Relates: #1168
---
Testing is done with the temp commit (due to pull_request_target)
https://github.com/cilium/proxy/actions/runs/16363994416?pr=1458
> gha: Add Cilium Gateway API tests

- cilium/api/npds.proto
- cilium/network_policy.cc
- cilium/network_policy.h
- go/cilium/api/npds.pb.go
- go/cilium/api/npds.pb.validate.go
- proxylib/proxylib/policymap.go
- tests/cilium_network_policy_test.cc
> [v1.34] policy: Support rule precedence

- cilium/api/npds.proto
- cilium/network_policy.cc
- cilium/network_policy.h
- go/cilium/api/npds.pb.go
- go/cilium/api/npds.pb.validate.go
- proxylib/proxylib/policymap.go
- tests/cilium_network_policy_test.cc
> [v1.33] policy: Support rule precedence

- envoy_build_config/extensions_build_config.bzl
> extensions: Enable compression and decompression

- tests/BUILD
- tests/cilium_websocket_policy_integration_test.cc
Add integration test with websocket passthtough.
> tests: Add cilium_websocket_policy_integration_test
