tools/install_bazel.sh
Some Bazel installations which are done not by the official script,
but i.e. from distribution packages created from tarballs, add
suffix to the version string. Example:
```
$ bazel version
Build label: 0.19.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 7 12:00:00 2018 (1541592000)
Build timestamp: 1541592000
Build timestamp as int: 1541592000
```
To prevent unnecessary Bazel installations, this change matches
BAZEL_VERSION string instead of comparing.
Signed-off-by: Michal Rostecki <mrostecki@suse.de>
=> tools: Match BAZEL_VERSION string instead of comparing

envoy_bootstrap_tmpl.json
Add missing quotation marks to the bootstrap template.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
=> Istio: Fix bootstrap template

Dockerfile.istio_proxy.in
Istio proxy image runs on older glibc (2.23), while our Envoy build requires 2.27.
Fix this for now by updating the glibc in the docker image. This bloats the image,
so a better solution is needed for a release.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
=> Istio: Upgrade glibc to 2.27

README.md
This repository is ready to use and all information about Cilium Envoy
filters are already removed from the main Cilium repo.
Signed-off-by: Michal Rostecki <mrostecki@suse.de>
=> readme: Add basic information about repository

linux/type_mapper.h
'__aligned_u64' redefined causes the compilation fail
with the following error:
"./linux/type_mapper.h:16: error: "__aligned_u64" redefined [-Werror]"
Signed-off-by: Jianlin Lv <Jianlin.Lv@arm.com>
=> Fix proxy compilation failure on arm64

tools/install_bazel.sh
Add aarch64 support for tools/install_bazel.sh
which would install aarch64 release of Bazel when
meets arm64 platform.
Signed-off-by: trevor tao <trevor.tao@arm.com>
=> Add aarch64 support for Bazel install

Dockerfile.builder.multi_arch, Dockerfile.multi_arch, Makefile, tools/push_manifest.sh
Add Arm64 Support for Envoy image building
Add Arm64 Dockerfile.builder and Dockerfile support for
image building on its builder and envoy image itself.
Uses multi-arch enabled Dockerfile.builder and Dockerfile to
enable image building on both amd64 and arm64 platform.
The multi-arch support with fat-manifest for both arm64 and amd64
is also added, i.e.,after pushing the images for the 2 arches,
we can just use the cmds:
make envoy-builder-manifest
make docker-envoy-manifest
to enable multi-arch of both images which would greatly
facilitate the image pulling and use.
This patch would not affect the current use and building
for those of x86_64 platform with the following consideration:
1. The current 'amd64' arched images would be tagged as the
default images as the original;
2. The …
=> Add Arm64 Support for Envoy image building

cilium/proxylib.cc
Hi, 
While I am writing my own golang share module under proxylib, I find it might be a bug that the need_bytes_ isn't reset across message boundaries.
The problem I encountered is my golang share module will not be called if the current input length is smaller than the need_bytes_  which is requested in the previous boundary.
So I think the need_bytes_ should be reset once the input length is fulfilled and not carry to next boundary.
=> proxylib: Reset the need_bytes_ after requested input_len being fulfilled

.github/workflows/cache-build.yaml, cilium/accesslog.cc, cilium/api/accesslog.proto, tests/accesslog_test.cc
Do not repeat any other request headers than `x-request-id` in response access logs.
=> accesslog: Only include x-request-id request header for response access logs

cilium/socket_option.h
Add SO_REUSEADDR to upstream connections when original source address
is used. This is needed to allow bind() to succeed before connect() if
a previous socket using the same source address and port is in
TIME_WAIT state when performing a retry, possibly to a different
destination host.
=> Add SO_REUSEADDR to upstream connections to fix failing retries

WORKSPACE, cilium/BUILD, cilium/accesslog.cc, cilium/accesslog.h, cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/l7policy.cc, cilium/l7policy.h, cilium/network_filter.cc, cilium/network_filter.h, cilium/network_policy.cc, cilium/network_policy.h, cilium/socket_option.h, cilium/tls_wrapper.cc, patches/envoy-upstream-http-auth.patch, patches/envoy-upstream-network-auth.patch, tests/accesslog_test.cc, tests/bpf_metadata.cc, tests/bpf_metadata.h, tests/cilium_http_integration.cc, tests/cilium_http_integration.h, tests/cilium_http_integration_test.cc, tests/cilium_tcp_integration.cc, tests/cilium_tcp_integration.h, tests/cilium_tcp_integration_test.cc, tests/cilium_tls_http_integration_test.cc, tests/cilium_tls_tcp_integration_test.cc
Add upstream authorization callbacks to Envoy and use them for policy enforcement.
Resolve policy dynamically so that policy changes take effect during long lasting HTTP connections.
=> Use upstream callbacks

cilium/accesslog.cc, cilium/accesslog.h, cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/l7policy.cc, cilium/network_policy.cc, cilium/network_policy.h, cilium/socket_option.h
Cilium Ingress forwards traffic via an Envoy listener on a NodePort, to
service backends in the cluster. Typically this traffic comes from
external sources, which do not have an egress network policy within the
cluster. Allow all traffic in this case. Note that traffic from sources
that have a defined policy (such as pods in the cluster) still adheres to
that policy.
=> policy: Allow L7 LB egress without policy

cilium/bpf_metadata.cc, cilium/host_map.h
Identities for CIDR or FQDN policy based destinations are allocated
locally. These destinations are outside of the cluster and will see the
source address as masqueraded by the local node. This being the case do
not bother about using the original source address for these
destinations.
=> cilium: Do not use original source address for locally allocated destination identities

envoy_build_config/extensions_build_config.bzl
Enable the following Envoy extensions so that they can be used with Cilium Envoy Config CRDs:
- dynamic forward proxy
- http set metadata
- network connection limit
- SNI cluster & dynamic forward proxy
- TCP & HTTP upstreams
- rate limits (local and global)
=> envoy: Enable extensions for Cilium Envoy Config use

.github/workflows/build.yaml, .github/workflows/cache-build.yaml
This commit is to avoid using envoy version in builder image tag, mainly
to avoid chicken and egg issue if we are bumping envoy version.
Signed-off-by: Tam Mach <tam.mach@cilium.io>
This is step 1 of 2 phase commit, the next PR will move all builds to new tag, after this PR is merged.
=> gha: Avoid using Envoy version in builder image tag

cilium/bpf_metadata.cc
Set `SO_REUSEPORT` option to hopefully get rid of `EADDRNOTAVAIL` errors when binding to the original source address of a source pod.
=> upstream: Set SO_REUSEPORT when binding to a specific source address

cilium/accesslog.cc, cilium/accesslog.h
Reopen the socket in case of errors like "broken pipe". Prior to this
the accesslog socket was never reopened after errors.
=> accesslog: Recover from socket errors

go/envoy/extensions/transport_sockets/tls/v3/common.pb.go
Update the generated API to reflect changes in the last Envoy version bump.
=> api: update

.bazelrc, Dockerfile, Makefile, Makefile.api, Makefile.dev, Makefile.docker
Improvements mainly for local builds:
1. Use manual build stamping to force final binary linking even when no source files changed. This is needed to always make the version reported by Envoy match the SHA of the git repository, as required for Cilium Envoy version check. Modify make targets to also depend on the generated `SOURCE_VERSION`
2. Fix references to build archives also in Makefiles to mirror the change for version independent references on GH action workflows.
3. Remove unused docker cache references by default. Trying to fetch the non-existing cache took some valuable build time.
4. Add ~/go/bin to PATH so that API build works as expected. 
5.  Speed up builds by using the default docker syntax. This avoids the check/pull of docker/dockerfile:1.2 in the beginning of the build, …
=> Build improvements

WORKSPACE
No functional changes since Envoy 1.21.5 release.
=> test: Bump Envoy to update expired CI certs

.github/workflows/cache-build.yaml, .github/workflows/test.yaml
Cilium master currently has a breaking change that causes proxylib built
from there not work on Ubuntu 20.04:
"cilium.network: Cannot load go module 'proxylib/libcilium.so': /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by proxylib/libcilium.so)"
Revert to pulling proxylib from latest stable release instead. This
will make tests fail if they depend on any updates on proxylib.so since
the latest stable release. This happens rarely, though, and we can
revisit this issue at that time.
=> github: Pull proxylib from stable for tests

WORKSPACE, cilium/network_filter.cc, cilium/tls_wrapper.cc, patches/0001-router-Do-not-crash-if-SNI-was-already-set-with-auto.patch
TCP proxy filter uses the SNI metadata on initialization before upstream callbacks are called. Thus we need to pass the SNI metadata in onNewConnection(), before the upstream callback gets called. Only set the metadata if not already set.
Apply a patch that prevents Envoy crash if auto_san option is used and metadata is already set, e.g., by Cilium network filter.
=> network_filter: Pass SNI before upstream callback

cilium/bpf_metadata.cc
=> bpf_metadata: Support localhost addresses as TPROXY listener addresses

.github/workflows/cache-build.yaml, Dockerfile, Dockerfile.tests, Makefile.docker
Build test and build archives from scratch on master push to avoid accumulating unused files in the build caches.
This is now possible due to the large runners and more efficient compiling with clang.
Also push test logs on successful test runs for reference. Failing runs will not complete the docker build step, so no test logs will be pushed, but those can be observed from the build logs on Github.
=> GH actions: build from scratch and persist test logs for successful test runs

.github/workflows/cache-build.yaml
Currently we run one job per core on bazel builds, half for amd64 build and the second half for arm64 build. This is 50% slower than when testing with double the number of Bazel build jobs. Try to get closer to optimum by increasing the number of jobs by 50%.
=> gh: Increase number of Bazel jobs by 50%

.github/workflows/builder.yaml
Currently, we need to manually build and push images if there is change in bazel version or builder Dockerfile. This is to avoid such manual step.
Signed-off-by: Tam Mach <tam.mach@cilium.io>
=> gha: Add jobs for bazel builder image

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml, .github/workflows/ci-tests.yaml, Dockerfile.builder.tests, Dockerfile.builder.tests.dockerignore, Makefile.docker
As cilium 1.13 is released today, the cilium/cilium:stable tag is moved to 1.13 as well. This will cause below issue for proxylib due glibc version. So we need to bump ubuntu version to 22.04 for test image, kindly note that the main cilium-envoy is still built with ubuntu 20.04 for backward compatibility of old cilium releases.
```
[external/envoy/source/common/config/filesystem_subscription_impl.cc:60] Filesystem config update rejected: Error adding/updating listener(s) tcp_proxy: cilium.network: Cannot load go module 'proxylib/libcilium.so': /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by proxylib/libcilium.so)
```
Fixes: https://github.com/cilium/proxy/issues/120
Fixes: https://github.com/cilium/proxy/issues/88
Testing with the temp commit (i.e. …
=> tests: Fix integration tests due to glibc

Makefile.api
Ubuntu 22.04 ships with Gnu make 4.3, which broke 'make api'.
Change the method of adding a space to a make variable to be compatible with Gnu make 4.3, which introduced this breaking change:
* WARNING: Backward-incompatibility! Previously appending using '+=' to an empty variable would result in a value starting with a space.  Now the initial space is only added if the variable already contains some value.  Similarly, appending an empty string does not add a trailing space.
Previously we relied on appending an empty string adding a trailing space. Now we use an empty variable as a delimiter to the same effect. Verified to work on both Gnu make 4.3 and Gnu make 4.2.1, which ships with Ubuntu 20.04.
=> make: Fix 'make api' for Gnu make 4.3

Dockerfile.tests, Makefile, Makefile.dev, Makefile.docker, README.md
Use correct archive image also for local docker tests launched via `make`.
Pass `NO_CACHE` to docker tests so that build cache can be cleared if it becomes corrupted.
Reintroduce jobs limit for local testing based on system memory. It appears that also with clang compiling some of the test sources takes a lot of memory, and the build was killed as too many parallel jobs exhausted system memory.
Finally, check that bazel and clang-15 are installed, and pull them automatically if needed when running `make`. This streamlines local building and testing on a fresh VM.
=> Fix local docker tests

.bazelrc, Dockerfile.tests
Changes in LD_LIBRARY_PATH value invalidate remote and disk caching. Currently we only set LD_LIBRARY_PATH to a specific value and in specific situations (for running cross-compiled tests). This causes archived test artefacts be ignored and rebuilt.
Typical scenario where this happened was CI cross-compiled artefacts for arm64 being ignored for local test runs on arm64.
Allow cached builds to be used in all test scenarios by always defining LD_LIBRARY_PATH=/usr/cilium-cross-compat/lib in the test environment. The path does not need to exist, but can be created (as a symlink) when needed for running cross-compiled tests.
=> tests: Always have test environment with LD_LIBRARY_PATH defined

.gitignore, Vagrantfile
Currently, bazel configuration requires clang-15 in specific path (e.g. /usr/bin/clang-15), which might not work well for non-ubuntu local machine. This commit is to add Vagrantfile to facilitate local dev.
Testing was done locally with the below command
```
$ VM_MEMORY=16000 VM_CPUS=8 vagrant up
```
=> dev: Add Vagrant file with ubuntu

Dockerfile, Dockerfile.dockerignore, Dockerfile.tests, Dockerfile.tests.dockerignore, Makefile, Makefile.docker
Build with debug symbols if DEBUG is defined, both in local bazel targets as well as docker targets.
This makes Envoy backtraces more meaningful which is nice when chasing a crashing bug.
=> Enable debug builds

Makefile
This is to add local_test_jobs flag in BAZEL_TEST_OPTS for below points:
- Build is still running in parallel
- Test is running with limited local_test_jobs to avoid any potential issue mentioned in #139.
Fixes: #139
=> test: Limit number of jobs running test

WORKSPACE
Regular update for v1.23 envoy proxy, also to test the recently added release GHA pipeline.
=> envoy: Bump to version v1.23.6

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml, .github/workflows/ci-tests.yaml, Dockerfile.tests
This is to add one more tag for docker artifact, following the below convention.
```
quay.io/cilium/cilium-envoy:v1.24-<commit-sha>
```
=> gha: Add envoy minor version tag in docker

.github/workflows/build-envoy-images-release.yaml
This was missed in previous PR, hence there is failure in master branch.
Fixes: 5268dd06fa156599cc20ca509fa64313cb013c3e
```
ERROR: invalid tag "quay.io/cilium/cilium-envoy:-5268dd06fa156599cc20ca509fa64313cb013c3e": invalid reference format
```
=> gha: Add ENVOY_MINOR_RELEASE for build task

WORKSPACE
Upstream release https://github.com/envoyproxy/envoy/releases/tag/v1.23.7
=> envoy: Bump envoy version to v1.23.7

.github/workflows/cilium-integration-tests.yaml
This commit introduces a GitHub Actions workflow which executes the Cilium integration tests.
The actual integration test performs the following steps:
* checking out Cilium repo (default: master)
* installing cilium via Cilium CLI (default: latest)
* setting up a kind cluster
* patching Cilium Agent Dockerfile with Proxy image of current branch
* building and pushing the Cilium images with the modified Envoy Proxy
* performing the Cilium connectivity tests
The following events are triggering the workflow:
* push to master
* opening pull request targeting master (https://github.com/cilium/proxy/actions/runs/4616447297/jobs/8161468972?pr=153)
* commenting on pull request with the option to override versions of Cilium & Cilium CLI (`/test-cilium-integration
[cilium=<ciliumRepoRef>] …
=> ci: introduce cilium integration test

.github/workflows/cilium-integration-tests.yaml
Cilium Integration Tests via comment should only be triggered if the author of the comment is owner, collaborator or member.
=> ci: Trigger Cilium Integration Tests via comment only by known users

.github/workflows/cilium-integration-tests.yaml
Event type payload "issue_comment" doesn't contain the head SHA of the PR of the comment directly. This results in the issue in the cilium integration tests, that `PROXY_TAG` isn't evaluated and the wait for the docker image times out.
This commit resolves the head SHA of the PR from the PR URL which solves the issue.
=> ci: get PR head SHA from PR URL in case of event type issue_comment

.github/workflows/cilium-integration-tests.yaml
When switching back to `pull_request_target` from `pull_request` before merging, the other occurances of event_name weren't adapted.
This commit fixes this.
=> ci: don't skip cilium integration tests on event pull_request_target

.github/workflows/cilium-integration-tests.yaml
Currently, when executing the Cilium Integration Tests, the Cilium repository is cloned from cilium/cilium.
To enable integration testing against a forked cilium repository, this commit introduces the possibility to configure the repository owner when triggering the Cilium Integration Tests via issue comment on the PR.
e.g. `/test-cilium-integration ciliumRepoOwner=<user>`
=> ci: Configurable cilium repo owner in Cilium Integration Tests

.github/workflows/cilium-integration-tests.yaml
Currently all Cilium Connectivity tests are executed when testing the Cilium Integration.
In the context of the Cilium Proxy, only the L7 tests are actually interesting. Therefore, this commit adds the necessary flag `--test=l7`.
=> ci: only execute L7 Connectivity tests when testing Cilium Integration

.github/workflows/cilium-integration-tests.yaml
Currently, the Cilium Integration test is installing Cilium CLI via Docker Image to support any given build of the CLI. The tar.gz only exist for actual CLI releases.
However, this comes with the drawback that referencing a stable release isn't that easy, because this needs knowledge of the actual GIT commit hash of the release.
Therefore, this commit installs the Cilium CLI via tar.gz when the Cilium CLI reference is a version (vx.x.x).
=> ci: cilium integration test supports stable version of cilium cli

.github/workflows/cilium-integration-tests.yaml
Currently the tag "test" is used when building the Cilium Agent & Operator Docker images during the Cilium Integration Tests.
This results in errors when the connectivity tests are trying to parse the tag as semantic version.
This commit uses the version from the VERSION file within the Cilium repository as version.
Even though we're fixing the version evaluation issue with https://github.com/cilium/cilium-cli/pull/1510 - it's probably a good idea to use a proper semver.
=> ci: Use Cilium Version as docker image tag in Cilium Integration Tests

WORKSPACE
This is for latest patch release from upstream envoy v1.23
https://github.com/envoyproxy/envoy/releases/tag/v1.23.8 https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.23/v1.23.8
=> envoy: Bump envoy version to v1.23.8

.github/renovate.json5, WORKSPACE, tools/code_format/config.yaml
This commit introduces automated Envoy version updates with Renovate on the master branch.
In addition, Envoy source code gets fetched via GIT clone instead of downloading the source archive.
Example Renovate PR Envoy `1.25.4` -> `1.25.5` (after a manual downgrade): https://github.com/mhofstetter/proxy/pull/2
-> updates on `v1.22` & `v1.23` release branches will be handled in a separate PR
=> Automated Envoy version updates with Renovate

.github/workflows/cilium-integration-tests.yaml
The new default branch `main` should be used in the cilium integration tests when cloning the cilium repository.
=> ci: adapt renamed default branch of cilium in integration tests

.github/renovate.json5
Currently, renovate tries to update envoy for all version types.
In most of the cases automated major & minor updates need some manual interaction anyway. Therefore, we start with patch releasese only - and disable major & minor ones.
=> ci: disable automated renovate updates for major & minor envoy versions

.github/workflows/cilium-integration-tests.yaml
This commit fixes the sysdump path when uploading the sysdump in case of a failure after the cilium integration tests.
Without this fix, the sysdump gets collected but not uploaded.
=> ci: fix sysdump collection path

.github/renovate.json5, Dockerfile
Currently, the docker image quay.io/cilium/cilium-envoy builds on top of plain scratch and only contains the cilium-envoy binary. It's only used for "transport" purposes.
With the introduction of a dedicated DaemonSet for Envoy in the context of Cilium, it becomes necessary to add a "runtime" to the cilium envoy docker image. This commit starts off by using Ubuntu. In a next step, we might try to use a smaller base image.
=> image: use ubuntu-22 as base image instead of scratch

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml, .github/workflows/ci-tests.yaml
With the rename of the default GIT branch from `master` to `main`, we should also change the tag of the envoy builder images.
Otherwise local builds fail to fetch the image.
```
❯ make docker-image-envoy
...
=> ERROR [internal] load metadata for quay.io/cilium/cilium-envoy-builder:main-archive-latest     
...
ERROR: failed to solve: quay.io/cilium/cilium-envoy-builder:main-archive-latest: quay.io/cilium/cilium-envoy-builder:main-archive-latest: not found
```
=> ci: rename master-archive-latest to main-archive-latest

WORKSPACE
This PR prepares and enables automated envoy version updates on the release branch v.1.23.
The renovate configuration on main branch ensures that the Envoy version will stay on v1.23.x (https://github.com/cilium/proxy/pull/193)
=> Automated Envoy version updates with Renovate on v1.23

.github/renovate.json5
This commit prevents renovate from updating or pinning `quay.io/cilium/cilium-envoy-builder` within the `Dockerfile`.
=> renovate: prevent updates of quay.io/cilium/cilium-envoy-builder

.github/renovate.json5
This commit enables renovate updates on release branches (currently v1.22 & v1.23).
* GitHub Actions -> should be ok
* Dockerfile.Builder -> mainly ubuntu -> which will stay on version 20.04
* Dockerfile -> scratch anyway
* envoy version -> configured to keep the envoy version on the corresponding minor versions.
=> renovate: enable renovate updates on release branches

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml
Having added ubuntu as runtime to the docker image - it's now possible to retrieve the envoy version directly by executing the command in the docker container instead of copying the binary from a running container.
In addition, Envoy's patch version is used for the check - instead of the minor version.
=> ci: use dockerimage directly for envoy binary version check

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml
This commit removes the interactive flag when executing the envoy version check to prevent the error `The input device is not a TTY`.
fixes: https://github.com/cilium/proxy/pull/190
=> ci: fix envoy version check issue

.github/workflows/build-envoy-images-release.yaml
Currently, an image of a release gets tagged and pushed with `latest`, `<SHA>` & `<envoy-minor-version>-<SHA>`.
In addition, this commit adds the format `<envoy-patch-version>-<SHA>` which then can be used in the cilium envoy daemonset.
=> image: push release image with envoy patch version

.github/workflows/cilium-integration-tests.yaml
Currently, the sed command which patches the Envoy image within the CIlium Agent File is no longer working. Therefore, the test doesn't get executed with the image of the current build.
This commit fixes the sed command and introduces a check - which fails if the Dockerfile doesn't get changed at all.
=> ci: fix agent dockerfile patch during Cilium Integration Test

.github/renovate.json5, .github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml
This PR implements container image signing using cosign.
=> ci: sign container image with cosign

Dockerfile
CA certificates may be needed for certificate validation. When they are installed, Envoy can be told to use the CA certs in the file system by creating a file-based Envoy secret:
```
secrets:
- name: validation_context
validation_context:
trusted_ca:
filename: /etc/ssl/certs/ca-certificates.crt
```
This can then be referred to in TLS config:
```
transport_socket:
name: envoy.transport_sockets.tls
typed_config:
"@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
common_tls_context:
validation_context_sds_secret_config:
name: validation_context
```
=> Dockerfile: Install ca-certificates package

envoy_build_config/extensions_build_config.bzl
Sync extensions with both our v1.23 and upstream release/v1.25.
- enable all extensions that were already enabled in v1.23
Enable internal listener extensions and additional HTTP URI/header match/rewrite new in v1.25 (vs. v1.23).
=> build: sync extensions, enable internal listener

cilium/grpc_subscription.cc, cilium/network_policy.cc, cilium/network_policy.h, cilium/secret_watcher.cc, cilium/secret_watcher.h, tests/bpf_metadata.cc, tests/bpf_metadata.h, tests/cilium_http_integration_test.cc, tests/cilium_network_policy_test.cc
Recently introduced SDS support for secrets in Cilium network policies causes an Envoy crash no assert failure due to a resource being freed on a different thread than where it was allocated. Fix this by processing policy updates on the main thread after all the worker threads have been updated. This was the last reference to an old policy is freed on the main thread, where all the policy objects are allocated.
Also limit the SDS initial fetch timeout to 5 seconds from the default 15 seconds.
=> Fix policy update crash

.github/renovate.json5
The branch v1.24 was cut recently for all cilium releases v1.11, v1.12 and v1.13. This commit is to update renovate for the same, also to clean up old release branches (v1.23 and v1.22).
Relates: https://github.com/cilium/proxy/pull/242
Relates: https://github.com/cilium/cilium/pull/26329
Relates: https://github.com/cilium/cilium/pull/26328
Relates: https://github.com/cilium/cilium/pull/26309
=> renovate: Add config for v1.24

.github/workflows/cilium-integration-tests.yaml
With [Cilium CLI v0.15.0](https://github.com/cilium/cilium-cli/releases/tag/v0.15.0), helm has become the new default installation mode.
This commit adapts this changes in the Cilium integration tests by replacing the usages of removed flags (`--config`, `--agent-image` & `--operator-image`) with `--helm-set`.
Otherwise, tests are failing with `unknown flag: --config`
=> cilium-integtest: adapt cilium installation to Cilium CLI helm mode

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml, .github/workflows/ci-tests.yaml, .github/workflows/cilium-integration-tests.yaml
If a GitHub Action workflow doesn't define explicit permissions, the token passed to the jobs can access all GitHub APIs.
Therefore, this commit introduces explicit permissions in all jobs.
=> ci: set explicit permissions in github action workflows

Makefile, Makefile.docker
We re-trigger GH actions on flaky tests anyway, so let bazel test retry them automatically. Optimally we would not have any test flakes, but in practice this seems beneficial.
=> bazel: Retry flaky tests

Makefile.docker
Fix the typo 'DOCKER_IMAGE_ENVOY_TAGS', which will also create image with tag 'latest-'{arch} for main branch.
=> build: Fix the main Envoy image tag name

Makefile.docker
$(BRANCH_TAG) is not a string variable, it doesn't have double quotation marks (" ").
So main branch image name will be:
EPOSITORY              TAG                                              IMAGE ID       CREATED         SIZE
cilium-envoy-dev       8067d6fc81a0c311e7f7d231df94f8d1e21b13b8-amd64   305681f66b7b   6 minutes ago   134MB
cilium-envoy-dev       main-amd64                                       305681f66b7b   6 minutes ago   134MB
But the design should be:
REPOSITORY             TAG                                              IMAGE ID       CREATED         SIZE
cilium-envoy           8067d6fc81a0c311e7f7d231df94f8d1e21b13b8-amd64   305681f66b7b   7 minutes ago   134MB
cilium-envoy           latest-amd64                                     305681f66b7b   7 minutes ago   134MB
=> build: Fix locally build docker images name on main branch

Dockerfile.dockerignore
When run `make docker-builder-archive` to update the pre-compiled Envoy dependencies, the dockerignore file is automatically updated with item '/proxylib/libcilium.so*'.
The commit 6c702baceef6 ("proxylib: Move proxylib from cilium to proxy repo") has added the '/proxylib/libcilium.so*' git ignore file name pattern.
=> dockerignore: Add the missed file when make docker-builder-archive

Dockerfile.builder.tests, Vagrantfile
Add libcap-dev also in Dockerfile.builder.tests and Vagrantfile.
libcap is needed for the <sys/capability.h> header, the library is not linked in,
as there are no cross-compiled packages for it.
=> build: Add libcap-dev also for tests and vagrant

Makefile.docker
New Docker desktop may have a default builder with name "desktop-linux" that is not buildx capable. Detect that name as well as the old "default" for the need to create a new buildx builder.
This is the same change we already did for `cilium/cilium` in https://github.com/cilium/cilium/pull/25908.
=> docker: Detect default "desktop-linux" builder

cilium/ipcache.cc
Sync ipcache map value definition with cilium main. Only the first member is used, so this should have no functional difference.
=> ipcache: Sync map value definition with cilium main

Dockerfile.builder, Dockerfile.builder.tests, Makefile, Vagrantfile
Use apt-add-repository instead of directly editing apt sources files, as this is less error prone.
Without this I had the makefile adding multiple lines in a fresh VM where llvm install got into a
weird state. With this change the llvm source will appear at most once in the sources list.
=> build: Use apt-add-repository

Dockerfile
This is to sync up with upstream cilium builder image in v1.14. Long term fix will be tracked under https://github.com/cilium/proxy/issues/308
=> image: Bump proxylib builder image

proxylib/proxylib/policymap.go
Parse deprecated 64-bit remote policy IDs also in proxylib.
Without this fix any old Cilium agent that has not been recompiled will fail to install proxylib (e.g., Kafka) policies correctly.
Fixes: #309
=> proxylib: Parse depcerated 64-bit remote policy IDs

Dockerfile.tests
With https://github.com/cilium/proxy/pull/324, the `Dockerfile.tests` has been changed that only the test-`runner` has access to the `libcilium.so` file.
But `make envoy-test-deps` (that is only executed on `main`) needs the file too. see https://github.com/cilium/proxy/actions/runs/6120782331/job/16616360145
Therefore, this commit adds the `libcilium.so` to the test-`builder` too.
=> dockerfile.tests: add libcilium.so for make envoy-test-deps

.github/workflows/cilium-integration-tests.yaml
Trying to `go get github.com/cilium/proxy` fails on PRs where the source is a forked repository. It tries to resolve the SHA from the forked repository on `github.com/cilium/proxy`.
Therefore, this commit introduces the env variable `PROXY_GITHUB_REPO` that gets set with the correct url - depending on the GHA trigger.
=> cilium-integration-test: dynamic go get github repo

.github/renovate.json5
integration tests (cilium/cilium) -> pinned to 1.21.x
cilium/proxy (proxylib) -> pinned to 1.20.x
-> once we move the proxylib (cilium/proxy) to go v1.21.x - we should enable go version upgrades in the `go.mod` file too.
=> renovate: pin minor go version in GitHub actions

.github/renovate.json5
Renovate version 36 introduced `matchFileNames` that should be used to properly match filenames.
```
matchPaths and matchFiles are now combined into matchFileNames, supporting exact match and glob-only.
The "any string match" functionality of matchPaths is now removed.
```
Therefore, this commit changes this and fixes an issue where filenames aren't matched properly.
=> renovate: migrate from matchFiles to matchFileNames

.github/workflows/cilium-integration-tests.yaml
#342 introduced a wrong github repo for the proxy
-> `cilium/cilium` instead of `cilium/proxy`
This commit fixes this.
=> cilium integ test: fix repo name

.github/renovate.json5
This commit fixes the renovate matchFilesPattern to match go-related workflow files.
=> renovate: fix go workflow file pattern

Dockerfile.tests
Target `builder-fresh` executes `make envoy-test-deps` to initialize the bazel cache. Therefore, it requires libcilium.so to be on the path.
Fixes: #324
=> dockerfile.tests: add libcilium to target builder-fresh

.github/workflows/cilium-integration-tests.yaml
If a PR is based on a forked github repository - updating the dependency fails with the following error.
```
go: github.com/mhofstetter/proxy@d904deb0a043a9d03889b801d6b81d3117f8ab7a (v0.0.0-20230911092536-d904deb0a043) requires github.com/mhofstetter/proxy@v0.0.0-20230911092536-d904deb0a043: parsing go.mod:
module declares its path as: github.com/cilium/proxy
but was required as: github.com/mhofstetter/proxy
```
In this case, a replacement needs to be placed in the go.mod file.
=> cilium integtest: fix cilium/proxy module update on forked repos

.gitignore, BUILD, Dockerfile, Dockerfile.builder, Dockerfile.builder.tests, Makefile, Vagrantfile, WORKSPACE, cilium/BUILD, cilium/bpf.cc, cilium/bpf.h, cilium/bpf_metadata.cc, cilium/network_filter.cc, cilium/privileged_service_client.cc, cilium/privileged_service_client.h, cilium/socket_option.h, patches/0004-listener-add-socket-options.patch, starter/BUILD, starter/main.cc, starter/privileged_service_protocol.cc, starter/privileged_service_protocol.h, starter/privileged_service_server.cc, starter/privileged_service_server.h
Introduce a `cilium-envoy-starter` that forks and execs `cilium-envoy`
after having dropped all privileges.
Perform bpf map and privileged socket option operations in
`cilium-envoy-starter`, as requested by Cilium filters running in
`cilium-envoy` via a pipe between the two. Currently the protocol over
this pipe supports only the following operations:
- dump capabilities cilium-envoy-starter is running with
- open bpf maps
- perform bpf map lookups
- set socket options
cilium-envoy-starter fails to start if it does not have adequate
privileges needed for the above operations.
cilium-envoy now exits if it is running with any privileges when Cilium
filters are first configured.
Implementation detail:
- `libcap` is not used, as it would be hard to cross-compile for both arm64
and amd64. …
=> Use `cilium-envoy-starter` to run Envoy without privileges

cilium/network_policy.cc
Currently, the networkpolicies in the Envoy config dump contains duplicates.
The reason is that the networkpolicies are stored per endpoint ip (e.g. IPv4 & IPv6). Iterating over the policies need to take this into account.
Therefore, this commit introduces a filter based on the endpoint id of the policy.
=> configdump: remove duplicates in networkpolicies config dump

.github/workflows/cilium-integration-tests.yaml
Cilium Integration Tests often hit the timeout of 30m waiting for the proxy images being available.
This commit increases the wait timeout to 45m.
-> https://github.com/cilium/proxy/commits/main ~ more or less all runs on `main`
=> cilium integration tests: increase "wait-for-images" timeout

.gitignore, Dockerfile, Makefile
If the build environment happens to have anything in the cache, it will not be built and does not get to the new bazel archive, so build a fresh archive without any caches.
Add a permissions check before the build to make sure /tmp/bazel-archive is accessible.
Prepare for incremental bazel archive updates by clearing the cache if critical build files have changed:
- define make target for BUILD_DEP_HASHES
- store this in bazel archive during archive build
- regenerate BUILD_DEP_HASHES when rebuilding bazel archive and clear the (old) bazel archive if there is any difference with the one stored in the archive.
=> gh: build fresh bazel archive without caches

.github/workflows/build-envoy-images-release.yaml, .github/workflows/ci-tests.yaml
We already added the --flaky_test_attempts=3 option to Makefile, in commit a1e0f93ca5 but failed to add this to GH workflows.
Fixes: #268
=> ci: Rerun flaky tests also in CI

.github/workflows/build-envoy-images-release.yaml, Dockerfile.dockerignore
Keep using the existing bazel archive as a basis as long as critical build dependencies have not changed.
=> gh: Reuse bazel archive on main merges

.github/workflows/build-envoy-images-release.yaml, Dockerfile, Dockerfile.tests, Dockerfile.tests.dockerignore
Reusing the build archive when merging to master seemes to work for the main build, so the same for tests.
=> gh: Reuse tests archive unless build environment has changed.

envoy_build_config/extensions_build_config.bzl
After this, and replacing out "commented out" (`sed 's/# "/"/g'`) the diff from this to upstream is:
```
190d189
<     "envoy.filters.network.client_ssl_auth":                      "//contrib/client_ssl_auth/filters/network/source:config",
199d197
<     "envoy.filters.network.mysql_proxy":                          "//contrib/mysql_proxy/filters/network/source:config",
472,476c470,472
< EXTENSION_CONFIG_VISIBILITY = ["//visibility:public"]
< EXTENSION_PACKAGE_VISIBILITY = ["//visibility:public"]
< CONTRIB_EXTENSION_PACKAGE_VISIBILITY = ["//visibility:public"]
<
< # We don't want to build for mobile, so just make the visibility private.
---
> EXTENSION_CONFIG_VISIBILITY = ["//:extension_config", "//:contrib_library", "//:examples_library", "//:mobile_library"]
> EXTENSION_PACKAGE_VISIBILITY …
```
=> build: Remove extra whitespace from extensions build config

Dockerfile, Dockerfile.tests
Store ENVOY_VERSION in bazel archive and report any version mismatch when building. This may help debug problems where builds fail or take a long time due to mismatching Envoy versions.
Note that PR builds for a new Envoy version use the old bazel archive to minimize the build time. When a new Envoy version is merged to main the bazel cache is deliberately built from scratch to keep it smaller.
=> docker: Store ENVOY_VERSION in bazel cache

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml, .github/workflows/ci-tests.yaml, .github/workflows/cilium-integration-tests.yaml
Use the release branch name instead of the main in archive tags, like in v1.24.
=> v1.25: Fix archive tags to not collide with main

Makefile.dev
Envoy v1.27.1 changed how clang-format is run. It is now run through
bazel rather than from the host environment. Adjust make targets
`check` and `fix` accordingly.
Exclude `envoy_build_config` from format checks to keep it as close to
upstream formatting as possible even when we have commented out
extensions.
=> Format fix v1.27.1

.github/workflows/ci-check-format.yaml
Apperently '!' needs to be escaped in yaml.
=> gh: Escape ! in workflow shell line

.github/renovate.json5
This commit enables renovate updates on the branch v1.26.
=> renovate: enable for branch v1.26

.github/renovate.json5
This comit pins the ubuntu version to 22.04 on v1.26.
=> renovate: pin ubuntu to version 22.04 in dockerfile on v1.26

README.md
Added a note in the README on how to make Envoy work on Raspberry Pi. This involves a small change to the compiler options and hinting at using the image in the Helm config.
=> Add a note on compiling for Raspberry Pi

patches/0002-upstream-Add-callback-for-upstream-authorization.patch
This commit is to remove duplicated callback for method onUpstreamConnectionEstablished.
Relates: https://github.com/envoyproxy/envoy/blob/release/v1.28/source/common/router/upstream_request.cc#L682-L684
Relates: https://github.com/cilium/proxy/pull/324
Signed-off-by: Tam Mach <tam.mach@cilium.io>
=> patches: Remove duplicated upstream callbacks

tests/cilium_http_integration_test.cc
There is an inherent race between file-based policy update and the following test cases. Reduce flakiness by adding 100ms sleep after changing policy files.
=> tests: Reduce flakiness

cilium/bpf_metadata.cc, cilium/network_filter.cc, cilium/network_policy.cc, cilium/network_policy.h, cilium/socket_option.h, proxylib/proxylib/instance.go, proxylib/proxylib/policymap.go, proxylib/test/accesslog_server.go
We no longer build proxy images for istio, better just clean it up.
Hence, as an additional follow up to #448, this commit removes the Istio sidecar specific implementations (socket mark, ...).
=> cleanup: remove istio sidecar related code

Makefile.docker, README.md
Currently, building the Cilium Proxy via `make docker-image-envoy` fails with the following error if the user isn't authenticated to the remote container registry (Quay).
```
❯ make docker-image-envoy
...
=> => pushing layers                                                                                                                                                                                                                                                                                                                                  2.9s
------
> exporting to image:
------
ERROR: failed to solve: failed to push quay.io/cilium/cilium-envoy:a24135cdcd9c42eb2b4c9ab708a2c5b9bc47ea4c-amd64: unexpected status from POST request to https://quay.io/v2/cilium/cilium-envoy/blobs/uploads/: …
```
=> Build: Push image to local docker registry by default

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml, .github/workflows/ci-tests.yaml, .github/workflows/cilium-integration-tests.yaml
This PR cleans up some wordings in the github action workflows
- `master` -> `main`
- remove word `PR` in release pipeline
=> ci: github action naming cleanup

cilium/conntrack.cc
Currently, during BPF metadata extraction, the source security id gets resolved by looking up the ID in the conntrack and ipcache BPF map. (preferring conntrack, with a fallback to ipcache).
If the loglevel of the Cilium Proxy (Envoy) is set to `info` (default), this leads to the following logoutput.
```
[2024-03-27 08:06:10.227][27][info][filter] [cilium/conntrack.cc:229] cilium.bpf_metadata: IPv4 conntrack map global lookup failed: Success
```
This might confuses users - especially because there's no indication that this was only the first attempt in the conntrack map, without a signal that there's the fallback to the ipcache map. This gets visible once loglevel is set to `debug`.
```
[2024-03-27 08:06:10.227][27][info][filter] [cilium/conntrack.cc:229] cilium.bpf_metadata: IPv4 …
```
=> bpfmetadata: change loglevel of unsuccessful ct lookup from info to debug

cilium/conntrack.cc
Backport of https://github.com/cilium/proxy/pull/675
=> [v1.27] bpfmetadata: change loglevel of unsuccessful ct lookup from info to debug

.github/renovate.json5
We can merge this PR once upstream PRs are landed
- https://github.com/cilium/cilium/pull/31498
- https://github.com/cilium/cilium/pull/31007
Post-merge Task:
=> renovate: Remove configuration for v1.26

Makefile, Makefile.dev
This commit removes duplicated make targets
- `envoy-default` (from `Makefile.dev`) -> duplicate of `bazel-bin/cilium-envoy` (or `cilium-envoy`) (from `Makefile`)
- `envoy-debug` (from `Makefile.dev`) -> possible by using `DEBUG=1 make cilium-envoy`
(`Makefile` also contains the new targets for the starter application - these would be missing from `Makefile.dev`)
=> build: remove duplicated make targets

cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/network_policy.h
This PR refactors the function `BPFMetadata.getMetadata` by extracting logic into separate functions
- `resolveSourceIdentity`
- `getIPAddressPairFrom`
- `selectIPVersion`
In addition some small other refactorings were added. All of this should help to ease the understanding of this function and the BPFMetadata listener filter in general.
Please review the individual commits.
=> bpfmetadata: refactor getMetadata by extracting methods

envoy_build_config/extensions_build_config.bzl
Enable local_ratelimit and http_inspector listeners filters as they may come in handy in some situations and do not interfere with Cilium integration (like original_dst and original_src listener filters could).
=> build: Enable local_ratelimit and http_inspector listener filters

Makefile.api
We have Renovate updating Go dependencies now, so we do not need to track them manually in Makefile.api any more. After this change `make api` does not downgrade the dependencies any more.
=> api: Remove explicit go get in favor of Renovate

cilium/privileged_service_client.cc, starter/main.cc
Currently, the "starter" drops all capabilities before starting the Envoy process itself. This is mainly to prevent the Envoy process from having the capabilities `NET_ADMIN`, `SYS_ADMIN` etc.
But this change also comes with the drawback that it prevents Envoy from binding to privileged ports - because the capability `NET_BIND_SERVICE` gets dropped as well.
Therefore, this commit introduces a new flag `--keep-cap-net-bind-service` to the starter. If this flag is present, the capability `NET_BIND_SERVICE` is kept in the privileged and effective set for the Envoy process.
=> starter: introduce possibility to keep capability NET_BIND_SERVICE

starter/main.cc
Currently, in case of not passing the argument delimiter `--`, the arguments are added before the actual program name. This results in errors starting up Envoy.
This commit fixes this by inserting the arguments at the end.
Fixes: #650
=> starter: fix Envoy program and argument order

cilium/socket_option.h
Compute socket option hashKey over the original source address and port when available. This will cause different downstream connections to no longer share upstream connections. This may fix connectivity issues where proxy responses do not get back to the proxy due to the connection with the original source port is cleared from bpf conntrack.
Related `cilium/cilium` PR: https://github.com/cilium/cilium/pull/32270
Related: https://github.com/cilium/cilium/issues/27762
=> socket_option: Compute hash over source address and port

cilium/bpf_metadata.cc
Use the original source address if permitted even if the destination is external to the cluster.
=> bpf_metadata: Use original source address even if the destination is external

cilium/BUILD, cilium/bpf.cc, cilium/bpf.h, cilium/bpf_metadata.cc, cilium/grpc_subscription.cc, cilium/grpc_subscription.h, cilium/ipcache.cc, cilium/ipcache.h, cilium/network_policy.cc, cilium/network_policy.h
Reopen ipcache whenever a new NetworkPolicy stream is opened. This way we get access to the new ipcache after cilium agent restart.
=> Ipcache reopen on cilium restart

go.mod, go.sum, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/pipe.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/testsync.go, vendor/golang.org/x/net/http2/transport.go, vendor/modules.txt
This is to fix the below CVE.
```
ADVISORY             SEVERITY  PACKAGE           CURRENT VERSION  FIXED IN VERSION
GHSA-4v7x-pqxf-cx7m  Medium    golang.org/x/net  v0.21.0          0.23.0
GO-2024-2687         Unknown   golang.org/x/net  v0.21.0          0.23.0
```
=> gomod: Bump indirect dep x/net version to v0.23.0

WORKSPACE, cilium/socket_option.h, patches/0001-network-Add-callback-for-upstream-authorization.patch, patches/0002-tcp_proxy-Add-filter-state-proxy_read_before_connect.patch, patches/0003-listener-add-socket-options.patch, patches/0004-factory_base-Backport-is_upstream.patch, patches/0005-Patch-cel-cpp-to-not-break-build.patch, patches/0006-original_dst_cluster-Avoid-multiple-hosts-for-the-sa.patch
Original destination cluster creates Host instances for the destination addresses on-demand. When multiple worker threads need to forward to the same destination at the same time (as is possible with `curl --parallel`, for example), separate instances of the destination Host objects are created. Meanwhile, Envoy uses `HostSharedPtr` as a map key in connection pool containers, which leads to multiple different connections being created for the same destination, even from the same worker, as the originally used Host instance is replaced with another, depending on which worker thread gets to add their Host object to the shared cluster state first. Multiple connections to the same destination fail when the original source address and port is being used, as is typically needed for Cilium …
=> envoy: Patch original destination cluster to handle parallel host instantiation

WORKSPACE, cilium/BUILD, cilium/bpf.cc, cilium/bpf.h, cilium/bpf_metadata.cc, cilium/grpc_subscription.cc, cilium/grpc_subscription.h, cilium/ipcache.cc, cilium/ipcache.h, cilium/network_policy.cc, cilium/network_policy.h, cilium/socket_option.h, go.mod, go.sum, patches/0005-original_dst_cluster-Avoid-multiple-hosts-for-the-sa.patch, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/pipe.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/testsync.go, vendor/golang.org/x/net/http2/transport.go, vendor/modules.txt
```upstream-prs
742 785 787 778
```
=> v1.28 Backports 2024-06-01

cilium/bpf_metadata.cc, tests/bpf_metadata.cc, tests/metadata_config_test.cc
Do not try create host or policy maps if bpf_root is not configured. In this mode only egress traffic is allowed, if Cilium policy enforcement filters are also configured and destinations are assumed to not be local to the node so that it is safe to use the original source address if so configured.
Tests can't configure bpf path, but assume full functionality. Adjust test code to mitigate for the change.
=> bpf_metadata: Allow use without bpf

.github/workflows/build-envoy-images-release.yaml
This commit is to add another tag with source timestamp, the reason is to enable renovate update for any change (but not just envoy version upgrade), as renovate is comparing the tag versions from left to right.
After this PR  and small changes in cilium/cilium repo, we don't need to manually create below PRs anymore
https://github.com/cilium/cilium/pull/34327
https://github.com/cilium/cilium/pull/34328
https://github.com/cilium/cilium/pull/34329
=> envoy: Use latest directory commit timestamp as tag

cilium/tls_wrapper.cc
Currently TLS wrapper is only used when the policy should also specify a TLS context for the connection. Therefore we should never use a raw socket instead when the TLS context is not available.
=> tls_wrapper: Do not use raw socket if no policy is found

.github/renovate.json5
All of upstream stable releases are upgraded with v1.29+, additionally Envoy v1.28 will be EOL on 19th Oct 2024.
https://github.com/envoyproxy/envoy/blob/main/RELEASES.md
=> renovate: Retire v1.28 branch

cilium/network_policy.cc
Add a warning log if worker threads take longer than 100ms to update their network policy maps. This is to help identify cases like #958, where worker thread [20] took almost 20 seconds to start running the update.
Related: #958
=> policy: Add warning log if worker threads take longer than 100ms to update policy maps

cilium/network_policy.cc
Add a warning log if worker threads take longer than 100ms to update their network policy maps. This is to help identify cases like #958, where worker thread [20] took almost 20 seconds to start running the update.
Related: #958
=> policy: Add warning log if worker threads take longer than 100ms to update policies

WORKSPACE, patches/0006-googleurl-dep.patch
This is to fix the CI failure.
Relates: https://github.com/envoyproxy/envoy/pull/36515
=> ci: Update google dep URL

cilium/network_policy.cc
=> v1.29 Backports 2024-10-23

envoy_build_config/extensions_build_config.bzl
This could be useful on supporting passing through proxy protocol info to downstream.
=> build: Enable envoy.transport_sockets.upstream_proxy_protocol

cilium/network_policy.cc, tests/cilium_http_integration_test.cc, tests/cilium_http_upstream_integration_test.cc, tests/cilium_network_policy_test.cc
When a header is matched based on a SDS secret and there is no inline value to use as a backup, the verdict should be deny if the secret is missing. Also, if the secret value is empty, then the match should be a presence match only.
=> policy: Drop on missing SDS secret and no default value inline

.github/renovate.json5, .github/workflows/renovate-config-validator.yaml
This stable branch is now read-only, as all stable releases are now with envoy 1.30.x.
=> renovate: Remove config for v1.29

cilium/BUILD, cilium/api/bpf_metadata.proto, cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/l7policy.h, cilium/network_policy.cc, cilium/network_policy.h
Add policy stats for number of updates, rejected updates, and update time limit timeouts, as well as a histogram for the update time duration.
Make the update time limit configurable via BfpMetadata filter config, as the policy map is created from there. Default is the same as in Cilium Agent (100ms).
=> policy: Add stats

cilium/bpf_metadata.cc, cilium/network_filter.cc, cilium/network_policy.cc, cilium/network_policy.h, cilium/socket_option.h, cilium/tls_wrapper.cc, cilium/tls_wrapper.h, tests/bpf_metadata.cc, tests/cilium_network_policy_test.cc
Cilium tls_wrapper should allow raw socket to be used if policy allows without TLS context.
Also check for SNI when getting TLS context so that the one matching the SNI is used if multiple are available.
Add policy tests validating the policy functionality.
Fixes: #890
=> tls_wrapper: Use raw socket with non-TLS policy

.github/workflows/cilium-integration-tests.yaml, cilium/bpf_metadata.cc, cilium/network_filter.cc, cilium/network_policy.cc, cilium/network_policy.h, cilium/secret_watcher.cc, cilium/socket_option.h, cilium/tls_wrapper.cc, tests/bpf_metadata.cc, tests/metadata_config_test.cc
Remove the member `initial_policy_` from the Cilium `SocketOption` class, as that reference was possibly kept after the policy had already been deleted. This made it possible for the policy to be destructed from the worker thread, which can lead to Envoy crash.
`initial_policy_` was stored as we already did the policy lookup and the same policy is needed in other Cilium filters. Have the `cilium.network` and `cilium.tls_wrapper` filters do their own policy lookups instead, so that we do not need to keep the reference in `SocketOption`.
Worker threads do the policy lookup from their own thread local maps, which hold a reference to the policy. These thread local references are relinquished from post function during policy update, which will release worker thread's last reference to the …
=> policy: Do not store policy reference in Cilium socket option

.github/workflows/cilium-integration-tests.yaml, cilium/bpf_metadata.cc, cilium/network_filter.cc, cilium/network_policy.cc, cilium/network_policy.h, cilium/secret_watcher.cc, cilium/socket_option.h, cilium/tls_wrapper.cc, tests/bpf_metadata.cc, tests/metadata_config_test.cc
=> [v1.30] Socket option no policy reference

cilium/BUILD, cilium/bpf_metadata.cc, cilium/host_map.h, cilium/policy_id.h, cilium/socket_option.h
A shared_ptr policy_resolver_ holds on to the passed BpfMetadata::Config, which owns the policy map reference. This could keep the the policy map alive when the listeners are destructed, leading to the destruction of the policy map from a worker thread. Change policy_resolver_ to a weak pointer to resolve this.
=> socket_option: Change policy_resolver_ to a weak pointer

cilium/network_policy.cc, tests/cilium_network_policy_test.cc
Log an error instead of crashing when Cilium NetworkPolicy resources are destructed in a worker thread. Remove stacktrace that is not useful at all with release builds.
Prior to enabling use of SDS secrets running NetworkPolicy destructors in a worker thread did not cause visible problems, even though we had taken measures to not do that a long time ago. Now that references to the policy have been removed from the connection metadata (Cilium SocketOption) this should no longer trigger. Nonetheless, crashing Envoy is too drastic as the event may be survivable (as it apparently has been for a long time when running without SDS references in the policy).
Enable trace level logging for troubleshooting if this error ever occurs.
Fixes: #1010
=> policy: Change abort to an error log

.bazelrc, Makefile, README.md, WORKSPACE, patches/0007-tcp_proxy-Check-for-nullptr-in-watermark-ASSERTs.patch, tools/stack_decode.py
Include also non-test targets in the `envoy-test-deps` target in hopes to make running tests with the tests-archive faster.
Other miscellaneous fixes:
- Add a new patch to fix segfault in integration tests when compiled for debug by testing for nullptr in ASSERT (ASSERT is a no-op in release builds)
- Update tools/stack_decode.py (even though it seems to require a GCC debug build to work)
- Update main branch Envoy version in README.md
=> Tests build all targets

.github/renovate.json5
This is related to the below comment. Ideally, we will be able to bump ubuntu version to 24.04 onlt when all Cilium stable releases are with 24.04.
https://github.com/cilium/proxy/pull/1033#issuecomment-2526677354
=> renovate: Pin ubuntu version for v1.30 branch

go.mod
Downgrade to Go 1.22 for compatibility with Cilium 1.16
=> go: downgrade to 1.22 for compatibility with Cilium v1.16

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml, .github/workflows/ci-check-format.yaml, .github/workflows/ci-tests.yaml, .github/workflows/cilium-integration-tests.yaml, .github/workflows/renovate-config-validator.yaml
This is to limit the number of jobs running if there is a newer commit for the same branch/pr.
=> gha: Add concurrency group for all workflows

cilium/network_policy.cc, cilium/network_policy.h, tests/cilium_network_policy_test.cc
Simplify stats prefix so that this:
cilium.policymap.127.0.0.1.3.policy.updates_rejected
becomes:
cilium.policy.updates_rejected
=> policy: Remove node id from stats prefix

cilium/network_policy.cc, cilium/network_policy.h
Changes
* stats: rename `updates` to `updates_total`
* stats: different scopes for NPDS & cilium policie stats (`cilium.npds.` & `cilium.policy.`)
Example listing of related metrics as prometheus export
```
root@kind-worker:/home/cilium# cilium envoy admin metrics -f 'npds|policy'
envoy_cilium_npds_control_plane_rate_limit_enforced{} 0
envoy_cilium_npds_init_fetch_timeout{} 0
envoy_cilium_npds_update_attempt{} 2
envoy_cilium_npds_update_failure{} 0
envoy_cilium_npds_update_rejected{} 0
envoy_cilium_npds_update_success{} 1
envoy_cilium_policy_tls_wrapper_missing_policy{} 0
envoy_cilium_policy_updates_rejected{} 0
envoy_cilium_policy_updates_timed_out{} 0
envoy_cilium_policy_updates_total{} 1
envoy_cilium_npds_control_plane_connected_state{} 1 …
```
=> stats: cleanup policy stats names

cilium/bpf_metadata.cc, cilium/bpf_metadata.h, envoy_build_config/extensions_build_config.bzl
```
extensions: enable udp proxy
This commit enables the UDP proxy related envoy extensions.
* `UDPProxy` UDP listener filter
* `HTTPCapsule` UDP session filter
* `DynamicForwardProxy` UDP session filter
```
```
bpf_metadata: introduce udp bpf_metadata factory & instance
Currently, configuring a UDP listener (Envoy listener with socket
address protocol set to `udp`) with a UDPProxy in Envoy may
fail due to Envoy missing privileges to bind the listener
address.
The reason is that the Cilium Proxy uses a "starter" that drops all
privileged capabilities before forking the actual Envoy process
(See https://github.com/cilium/proxy/pull/315 for more details.) Setting up the necessary socket options
is part of the Cilium `BPFMetadata` listener filter.
The current `BPFMetadata` listener filter …
```
=> Enable UDP listener & proxy support

cilium/bpf_metadata.cc, cilium/bpf_metadata.h, envoy_build_config/extensions_build_config.bzl
=> v1.31 Backports 2024-12-19

WORKSPACE, cilium/network_policy.cc, cilium/network_policy.h, patches/0007-tcp_proxy-Check-for-nullptr-in-watermark-ASSERTs.patch, patches/0008-thread_local-reset-slot-in-worker-threads-first.patch
Add an upstream patch to make sure the policy map is destructed from the main thread. The changed behavior triggers only when all listeners with Cilium `bpf_metadata` filter are removed, and the listener drain time (default 10 minutes) passes.
=> Policy destruct in main thread

.gitignore
Currently, dotfiles are explictly git-ignored via `.gitignore` file.
Instead of adding additional ignores (e.g. direnv' `.envrc`), this commit adopts the upstream pattern of disallowing all dot files by default, and enable explictly.
See: https://github.com/envoyproxy/envoy/blob/main/.gitignore#L1
=> gitignore: disallow dot files by default and enable explictly

cilium/BUILD, cilium/l7policy.cc, cilium/socket_option.h
Currently, the dependency from `socket_option_lib` to `network_policy_lib` isn't explicitly declared in the `BUILD` file.
As a consequence, forward declarations for the types `PolicyInstance` & `PolicyInstanceConstSharedPtr` exist in `socket_option.h`.
Therefore, this commit is defining an explit module depencency and gets rid of the unnecessary forward declarations.
=> build: `socket_option_lib` depends on `network_policy_lib`

tools/install_bazelisk.sh
Currently, checking for an up-to-date version of bazlisk installs tries to download and install bazelisk whenever the version doesn't match the expected one.
This prevents developers from using bazelisk with the version `development` (locally build or installed via thirdparty tools (e.g. nix).
Therefore, this commit changes the logic to respect the version `development` in addition the the actually expected version.
=> makefile: install-bazelisk should respect development version

Makefile.dev
This commit replaces some occurrences of `bazel` with the variable `$(BAZEL)`.
=> makefile: use `$(BAZEL)` instead of `bazel`

cilium/conntrack.cc, cilium/conntrack.h
Upstream Envoy linting prevents usages of `std::mutex` in favor of `Thread::MutexBasicLockable`.
This error occurred while trying to cleanup the imports - and therefore adding the direct dependency to `<mutex>`.
```
ERROR: From ./cilium/conntrack.h
ERROR: ./cilium/conntrack.h:7: Don't use <mutex> or <condition_variable*>, switch to Thread::MutexBasicLockable in source/common/common/thread.h
ERROR: From ./cilium/conntrack.cc
ERROR: ./cilium/conntrack.cc:9: Don't use <mutex> or <condition_variable*>, switch to Thread::MutexBasicLockable in source/common/common/thread.h
ERROR: check format failed. diff has been applied'
```
See https://github.com/envoyproxy/envoy/blob/main/tools/code_format/check_format.py#L605-L610
```
report_error(
"Don't use <mutex> or <condition_variable*>, switch to " …
```
=> conntrack: replace std::mutex with Thread::MutexBasicLockable

cilium/socket_option.h
```
socket_options: combine setting IP_TRANSPARENT for ipv4 & ipv6
This commit reduces boilerplate by reducing the different codepaths
for setting the IP_TRANSPARENT socket option for IPv4 & IPv6.
```
```
socket_options: move comment for SO_REUSEADDR
This commit moves the comment about setting SO_REUSEADDR
socket option to the code that is actually setting the option.
```
=> socket_options: small cleanup regarding setting socket options (IP_TRANSPARENT & SO_REUSEADDR)

Makefile, WORKSPACE
Currently, the C++ toolchains (defined in `bazel/toolchains`) are automatically registered in the `WORKSPACE` file via `register_toolchains`.
Problem with this approach is that this is tightly coupled to the Cilium Proxy CI environment (Ubuntu & expected paths in `/usr/bin/...`). If these requirements aren't met, compilation with the evaluated C++ toolchain fails - even though there might be an available and compatible local toolchain.
To provide more flexibility in terms of development environment and integration, this commit removes the hardcoded registration of the toolchains in the `WORKSPACE` file and replaces it with an explicit registration via bazel build argument `--extra_toolchains="//bazel/toolchains:all"` where required / builded in docker (switch in `Makefile` via …
=> bazel: register c++ toolchains via build flag --extra_toolchains

.clangd, cilium/socket_option.h
Follow up of: https://github.com/cilium/proxy/pull/1100
=> clangd: prevent include of private headers that lead to problems

.bazelrc, cilium/grpc_subscription.cc, cilium/network_policy.cc, cilium/network_policy.h, cilium/secret_watcher.cc
Listeners using Cilium network policy enforcement are shared among all the pods in the node, so the listener initialization should not stall on policy update at all, as this prevents the listener from actually listening on it's listen port before the initial network policy update has completed.
Moreover, a network policy update can stall for a long time if the required SDS secrets are missing. Reduce the timeout for fetching secrets to 50ms (from 5 seconds) to not stall policy updates on the node due to a missing secret, as the effect of the missing secret is typically limited to a subset of pods, while stalling policy updates has negative effect on all pods using `toFQDNs` policies, for example.
Break up Envoy init manager functionality into helpers to make the business logic easier to …
=> policy: Remove initialization dependency from listener initialization

cilium/BUILD, cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/l7policy.cc, cilium/network_filter.cc, cilium/privileged_service_client.h, cilium/socket_option.h, cilium/socket_option_cilium_mark.h, cilium/socket_option_cilium_policy.h, cilium/socket_option_ip_transparent.h, cilium/socket_option_source_address.h, cilium/tls_wrapper.cc, cilium/websocket.cc, tests/bpf_metadata.cc, tests/bpf_metadata.h, tests/metadata_config_test.cc
This PR split the existing 2 socket options (SocketMarkOption & SocketOption (inherits from the first one)) into more fine-grain and cohesive socket options. In addition, upstream Envoy socket options are used where possible.
Please see the individual commits for details.
This split has the following advantages:
* Separate configuration of the individual socket options for listener- and connection sockets (instead of doing an in-socket-option decision based on the security id (0 = listener socket))
* Scope and responsibility of the socket options is clear and easier to understand (currently the all-in-one socket option is responsible to pass information to filters (via filter state), pass information to Cilium network- and http filters (via Envoy socket option functionality), configure …
=> bpf_metadata: cleanup socketoptions

cilium/api/bpf_metadata.proto, cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/conntrack.cc, cilium/conntrack.h, cilium/filter_state_cilium_policy.h, cilium/l7policy.cc, cilium/network_filter.cc, cilium/network_policy.cc, cilium/network_policy.h, cilium/tls_wrapper.cc, patches/0008-thread_local-reset-slot-in-worker-threads-first.patch, tests/bpf_metadata.cc, tests/cilium_http_integration_test.cc, tests/cilium_network_policy_test.cc, tests/metadata_config_test.cc
Currently we must execute in all worker threads to be able to ACK the update back to Cilium agent. This has become a problem as Envoy logs show worker threads stalling for 10 seconds doing nothing, pausing the policy update progress long enough to cause problems for FQDN policies.
Change to create a new policy map for each update, sharing it as a const map for all worker threads using an atomic swap. Deletion of the old map is coordinated with the worker threads in RCU fashion, waiting until each worker thread has processed a new posted function, proving that they no longer use the policy lookop results they may have obtained. This can be done after ACK is already sent back to Cilium Agent.
There is a potentially significant functional change, we no longer wait at all for SDS secrets to …
=> policy: Atomic swap for policy map

.bazelrc, .github/workflows/cilium-integration-tests.yaml, Makefile, WORKSPACE, cilium/bpf_metadata.cc, cilium/network_filter.cc, cilium/network_policy.cc, cilium/network_policy.h, cilium/secret_watcher.cc, cilium/socket_option.h, cilium/tls_wrapper.cc, patches/0007-tcp_proxy-Check-for-nullptr-in-watermark-ASSERTs.patch, patches/0008-thread_local-reset-slot-in-worker-threads-first.patch, tests/bpf_metadata.cc, tests/cilium_network_policy_test.cc, tests/metadata_config_test.cc, tools/stack_decode.py
_Note_: This backport PR consolidates all recent fixes related to SDS, we can push new commit if required.
Upstream testing is done in https://github.com/cilium/cilium/pull/36925
```upstream-prs
1010 1020 1021 1016 1023 1082
```
=> v1.30 Backports 2024-12-03

cilium/bpf_metadata.cc
SO_LINGER option makes the close() system call block if there is any unfinished business on the socket, even if the socket is set to the non-blocking mode. Any blocking is at odds with Envoy's threading model, and we have seen non-zero Envoy watchdog mege miss metrics corroborated by Envoy trace logs indicating that a close system call was blocking for 10 seconds, exactly the time we had set for the SO_LINGER option.
Fix this by removing the setting of the linger option.
Due to the different code structure v1.31 version is in a separate PR: https://github.com/cilium/proxy/pull/1128
=> Remove the SO_LINGER option

cilium/bpf_metadata.cc, cilium/bpf_metadata.h, tests/bpf_metadata.cc
Currently, the function `extractSocketMetadata` does not only extract relevant information from the socket and enriches it with data retrieved from BPF maps. It also has some side-effects: namely setting the proxylib protocol as application protocol on the network socket.
Therefore, this commit splits this logic from the function `extractSocketMetadata` and moves the part that is setting the proxylib l7 protocol as requested app protocol on the network socket into a dedicated function on the SocketMetadata struct that then is called from the BPF metadata listener filter in the onAccept function.
The part that is evaluating the ProxyLib L7 proto is still kept in the function `extractSocketMetadata`.
This way, we can keep the function extractSocketMetadata free of side-effects and bundle …
=> bpf_metadata: extract setting requested proxylib app protocol

cilium/bpf_metadata.cc
The refactoring of PR #1129 completely missed calling the newly introduced function `configureProxyLibApplicationProtocol` in the BPF metadata listener filter.
This commit fixes this.
Looks like the test coverage for the ProxyLib integration in the unit & connectivity tests is quite low - at least the ones that are executed. Probably worth to improve.
=> bpf_metadata: fix setting proxylib l7 protocol

tests/metadata_config_test.cc
This commit adds an unit test that verifies that the proxylib l7 protocol has been correctly set to the request application protocols of the network socket.
=> bpf_metadata: add unit-test for proxylib l7 proto

tests/bpf_metadata.cc
The logic that sets the proxylib l7 proto as requested application protocol on the network socket has been extracted from the function `extractSocketMetadata`.
But, the test bpfmetadata config still contains this functionality.
Therefore, this commit removes setting the requested application protocol on the network socket in the test bpfmetadata config. Tests that rely on this functionality should do this explicitly in the setup by calling the function `configureProxyLibApplicationProtocol` on the `SocketMetadata` struct.
Related to: https://github.com/cilium/proxy/pull/1129
=> bpf_metadata: cleanp proxylib in test bpfmetadata config

cilium/bpf_metadata.cc, cilium/bpf_metadata.h, tests/bpf_metadata.cc, tests/metadata_config_test.cc
Currently, `extractSocketMetadata` also restores the local address for the use by the `OriginalDestCluster`.
To keep the function free of side-effects, the logic that restores the local address gets extracted into a function within the `SocketMetadata` that gets called from the BPF metadata listener after extracting the BPF metadata from the socket.
=> bpf_metadata: extract restoreLocalAddress

cilium/bpf_metadata.cc
This commit adds the socket filedescriptor to the logmessage when entering the `onAccept` method on the BPFMetadata listener filter.
=> bpf_metadata: log socket fd in onAccept

cilium/l7policy.cc, cilium/network_filter.cc, cilium/websocket.cc
This commit changes some usages of `ENVOY_LOG` to `ENVOY_CONN_LOG` to improve correlation of application logs entries with a connection id.
=> logging: use ENVOY_CONN_LOG

cilium/bpf_metadata.h, cilium/socket_option_source_address.h
This commit aligns the logging for restoration of the local address for downstream & upstream socket by always logging the socket and the old & new local address.
=> bpf_metadata: align logging for restoration

cilium/BUILD, cilium/socket_option_cilium_mark.cc, cilium/socket_option_cilium_mark.h, cilium/socket_option_ip_transparent.cc, cilium/socket_option_ip_transparent.h, cilium/socket_option_source_address.cc, cilium/socket_option_source_address.h
```
socket_options: introduce C files
Currently, the socket options are completely defined in C++
header files. As a result, the bazel BUILD file misses some
dependencies that also result to clangd not working properly
for these files.
This commit prepares the split into C & Header files by introducing
the "empty" *.cc files and fixing the dependencies in the BUILD file.
In the next commit, the logic will be moved.
```
```
socket_options: move logic to C files
This commit moves the implementation of the socket options
into the *.cc files.
```
=> socket_options: introduce C files

cilium/bpf_metadata.cc
PR https://github.com/cilium/proxy/pull/1115 unintentionally changed that the keep alive socket options are no longer applied on the accepted downstream socket, instead (due to the usage of Envoy SocketOption) they are now applied on the corresponding upstream socket.
This commit is reverting this change and adds some helping comments to the code.
Note: Same would have applied for `SO_LINGER` - but this has been removed completely in the meantime with https://github.com/cilium/proxy/pull/1128
=> bpf_metadata: set TCP keep alive socket options without Envoy SocketOption

cilium/BUILD, cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/l7policy.cc, cilium/network_filter.cc, cilium/socket_option_cilium_mark.cc, cilium/socket_option_cilium_mark.h, cilium/socket_option_ip_transparent.cc, cilium/socket_option_ip_transparent.h, cilium/socket_option_source_address.cc, cilium/socket_option_source_address.h, cilium/websocket.cc, tests/bpf_metadata.cc, tests/metadata_config_test.cc
```upstream-prs
1132 1133 1142 1140 1143 1148 1151
```
=> v1.31 Backports 2025-01-28

cilium/l7policy.cc, cilium/network_filter.cc
PR https://github.com/cilium/proxy/pull/1140 introduced a regression where
logging fails on shadow upstream connections (Detected in Gateway API tests in cilium/cilium).
Therefore this PR is checking for shadowing connections and skips
enforcement & logging on them.
=> envoy: skip upstream handling on shadows

.github/workflows/cilium-integration-tests.yaml
Also the set-header tests were succeeding with `--curl-parallel=10` locally today, let's see if we can lock this in.
=> ci: use --curl-parallel=10 on cilium integration tests

.github/workflows/cilium-integration-tests.yaml
Some connectivity tests flake now that we added the `--curl-parallel=10` option. Make triaging easier by collecting a sysdump after each failure.
Add these cilium-cli options:
`--collect-sysdump-on-failure`: Collects a sysdump after each failure.
`--flush-ct`: Flush Cilium datapath connection tracking table on each node (before starting tests)
`--sysdump-hubble-flows-count=100000`: Bump up from the default (10000)
`--sysdump-hubble-flows-timeout=15s`: Bump up from the default (5s)
Rename the final sysdump to `cilium-sysdump-final` and change the workflow to collect all the generated sysdumps.
=> ci: Collect sysdump on failure in cilium integration test

cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/filter_state_cilium_policy.cc, cilium/filter_state_cilium_policy.h, cilium/l7policy.cc, cilium/network_filter.cc, cilium/network_policy.h, tests/bpf_metadata.cc, tests/metadata_config_test.cc
Enforce source pod's egress policy, if available, i.e., when the source is a local pod, even in the north/south scenario, where the Ingress IP is used as the upstream source address.
=> policy: Use source pod's egress policy if available

.github/workflows/cilium-integration-tests.yaml
This is to make it easier to change the value, without updating the codebase.
=> env: Set repo environment variable for curl parallel

.github/renovate.json5, Dockerfile
We still need builder image with ubuntu 22.04 till the oldest cilium/cilium is 1.17.
Testing is done in upstream https://github.com/cilium/cilium/pull/38137
Fixes: https://github.com/cilium/proxy/issues/1200
=> deps: Bump ubuntu runtime image to 24.04

.github/renovate.json5
This is just to make sure we don't intentionally upgrade go version, which may (or may not) break cilium/cilium upstream. If there is tangile benefit, we can remove such constraint later.
=> renovate: Allow golang <1.24

Makefile.docker
PR #951 removed the bazel version in docker tags.
This results in failures not finding the builder image when executing make targets like `make docker-image-envoy` as they still expect the bazel version in the tag.
Therefore, this commit is removing the bazel version from `BUILDER_BASE_TAG` & `TESTS_BUILDER_BASE_TAG`.
=> build: remove bazel image from BUILDER_BASE_TAG

Makefile
This is the extension of clang configuration, one benefit is to pretty much aligning with upstream envoy build.
=> build: Use libc++ configuration

.github/workflows/ci-tests.yaml
This variable is not used in github action workflow, so better just remove it.
Makefile derives the value from git command.
=> gha: Remove un-used command/env/file

.github/workflows/codeql.yml
Let's run it at the end of every Monday, we don't really need to care
about timezone.
=> code-ql: Add scheduled run weekly

.github/renovate.json5
All cilium stable branches are now with envoy 1.32+, so we can retire v1.31 stable branch now.
Relates: https://github.com/cilium/cilium/pull/38449
Relates: https://github.com/cilium/cilium/pull/38307
Relates: https://github.com/cilium/cilium/pull/38306
=> renovate: Retire v1.31 branch

cilium/network_policy.cc
This is to avoid the below issue, as local dev might be using GCC instead of clang.
```
cilium/network_policy.cc:1218: error: ignoring '#pragma clang diagnostic' [-Werror=unknown-pragmas]
1218 | #pragma clang diagnostic push
|
cilium/network_policy.cc:1219: error: ignoring '#pragma clang diagnostic' [-Werror=unknown-pragmas]
1219 | #pragma clang diagnostic ignored "-Wnull-dereference"
|
cilium/network_policy.cc:1221: error: ignoring '#pragma clang diagnostic' [-Werror=unknown-pragmas]
1221 | #pragma clang diagnostic pop
```
=> clang: Add clang macro check

cilium/network_policy.cc, cilium/network_policy.h, tests/cilium_network_policy_test.cc
This commit is to support domain matching logic for SNI.
Examples of valid matches:
"*.example.com" matches:
- "foo.example.com"
- "bar.example.com"
- "sub.example.com" 
but not:
- "example.com" as wildcard requires exactly one label
- "foo.bar.example.com" due to too many labels
- "notexample.com" due to different domain
=> sni: Add logic to allow pattern prefix match

.github/workflows/codeql.yml
We don't need to regenerate the API, just run the build
Fixes: #1246
Testing is done via https://github.com/cilium/proxy/actions/runs/14260547976
=> gha: Fix codeql build

cilium/network_policy.cc
=> v1.32 Backports 2025-04-09

cilium/tls_wrapper.cc
SDS secret unavailability is not the only reason for socket error, for example, port binding failure could be another reason. This commit is to change the confusing error message.
=> cilium: Update the generic error message

.github/workflows/cilium-integration-tests.yaml
Cilium stable branches are with cilium/proxy v1.32, while Cilium main branch is with cilium/proxy main. So it's better to test v1.32 with the oldest cilium supported version (e.g. v1.15) instead of main.
=> [v1.32] gha: Use the oldest Cilium supported version

cilium/filter_state_cilium_policy.cc
This will help to debug which policy allows/denies the traffic.
=> misc: Add ingress policy name in log

.github/workflows/build-envoy-images-release.yaml
This is to avoid the below issue
```
Error: buildx failed with: ERROR: invalid tag "quay.io/cilium/cilium-envoy-builder:": invalid reference format
```
=> gha: Update the Docker builder tag

.github/workflows/build-envoy-images-release.yaml
This will help to avoid the mistake when the new branch is cut, so that we don't run the build with the wrong archive/cache image.
=> gha: Avoid hard coded main in tag

.github/workflows/ci-clang-tidy.yaml
Use 'HEAD^1' instead of 'origin/main' as the git fetch is depth 2 only.
=> gh: Fix ambiguous reference to 'origin/main'

.github/workflows/cilium-integration-tests.yaml
Not a big deal but it's a bit faster now:
- [Before](https://github.com/cilium/proxy/actions/runs/15165303106/job/42641420030): ~13 min 
- [After](https://github.com/cilium/proxy/actions/runs/15166520621/job/42645662595?pr=1355): ~6 min
=> ci: run cilium tests concurrently

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/cilium-integration-tests.yaml
The goal is to avoid extra waiting time, while building the images.
Testing was done with temp commit, here is the sample run https://github.com/cilium/proxy/actions/runs/15178091834/job/42682174454?pr=1178
=> gha: Use workflow_call for Cilium Integration test

cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/filter_state_cilium_policy.cc, cilium/filter_state_cilium_policy.h, cilium/network_policy.cc, cilium/network_policy.h, cilium/secret_watcher.cc, cilium/secret_watcher.h, tests/bpf_metadata.cc, tests/cilium_network_policy_test.cc
Change policy resolver back to a shared pointer, and manage `NetworkPolicyMap` destruction explicitly by splitting the map to singleton and `NetworkPolicyMapImpl` and by posting the `NetworkPolicyMapImpl` to the main thread for deletion. This effectively reverts https://github.com/cilium/proxy/pull/1016.
`NetworkPolicyMapImpl` is managed via an unique_ptr, which required the removal of use of `shared_from_this`, which was possible due to simplified clean-up of the old map now that an atomic swap is used for the policy map update.
This change allows long lived connections on a removed listener to keep on functioning, including receiving policy updates via the singleton policy map.
=> Change policy resolver back to a shared pointer

cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/socket_option_source_address.cc, tests/metadata_config_test.cc
Source address socket option uses 'hashKey' function to choose the
upstream connection pool. 'hashKey' has no access to the socket (which
has not been created yet), so it needs access to the original source
address which can be either IPv4 or IPv6 to be able to pass in the
original source address and port in the resulting hash.
This fixes the issue with east/west l7lb that caused upstream connection
pool being shared between all local endpoints with the same security
identity, while using the original source address. This manifested as
connection pool attempting to create more than one connection with the
same 5-tuple, which failed and resulted in '503' responses in HTTP.
Fixes: #65
=> l7lb: Pass original source address in option for east/west

cilium/api/bpf_metadata.proto, cilium/bpf_metadata.cc, go/cilium/api/bpf_metadata.pb.go, go/cilium/api/bpf_metadata.pb.validate.go
Add new proto config option `use_nphds`, which, if`true`, will use the
Network Policy Hosts xDS protocol to pull IP/ID mappings from Cilium
Agent when use of bpf maps is not configured (i.e., `bpf_root` is left empty).
This retains the current behavior of not initializing the Network Policy
map if `bpf_root` is empty, and allows enforcement of Cilium Network
Policies without access to bpf maps by specifying the new `use_nphds` as
'true' in that case.
=> bpf_metadata: Add config `use_nphds`

cilium/BUILD, cilium/privileged_service_client.cc, cilium/privileged_service_client.h, starter/main.cc, starter/privileged_service_protocol.cc, starter/privileged_service_protocol.h, starter/privileged_service_server.cc
Change the calls to "privileged services" to only take the `calls_mutex_` for receiving responses.
Set up a `Waiter` for each caller so that the active receiver can pass responses to them. The active receiver stops receiving as soon as it gets its own response, and passes the receiver role to another "waiter".
Any changes to this code should be tested with a performance tool maximally loading all the available worker threads (e.g., `wrk`).
This partially addresses the performance regression introduced in #315.
On a local kind environment this improves `wrk -t50 -c100` request rate through a CEC-defined Envoy listener from 6221 req/sec to 13593 req/sec.
Fixes: #315
=> cilium: Reduce locking in privileged service client

cilium/accesslog.cc, cilium/bpf_metadata.h, cilium/filter_state_cilium_policy.cc, cilium/filter_state_cilium_policy.h, cilium/l7policy.cc, cilium/l7policy.h, cilium/network_filter.cc, cilium/network_filter.h, cilium/network_policy.cc, cilium/network_policy.h, tests/cilium_http_integration_test.cc, tests/cilium_network_policy_test.cc
Prepare network filter for future dual upstream/downstream change by only using the current upstream callback for L7 LB enforcement. Now that network level policy for non-L7 LB is performed directly in the downstream filter's onNewConnection() callback, the connection will be rejected on network policy deny before the HTTP level policy is enforced. Some tests needed to be updated to reflect this change by waiting for disconnect rather than HTTP '403' in these cases. This change also causes HTTP access logging to not happen to any traffic that is already dropped by the network level policy. Note that for L7 LB (i.e., Ingress, Gateway API) there is no change.
The case where this change could have production difference is when the network level policy rule enforces an SNI, as in these cases …
=> Policy refactor to fix logging, avoid unnecessary steps

.github/renovate.json5
Branch v1.33 is cut, main is now with 1.34.
Relates: https://github.com/cilium/proxy/pull/1302
=> renovate: Add config for v1.33

envoy_build_config/extensions_build_config.bzl
This commit enables the DNS cluster extension that should be used to configure DNS cluster-related aspects instead of doing this directly via deprecated properties on the cluster.
=> extensions: enable DNS cluster extension

.github/renovate.json5
The main reason is glibc dependency, we will perform the upgrade only after cilium 1.17 is the oldest supported version.
=> renovate: Use ubuntu 22.04 only for builder

cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/filter_state_cilium_policy.h, cilium/socket_option_source_address.cc, cilium/socket_option_source_address.h
We already skip using the original source address/port for non-L7 LB destinations in the same node. This is needed to avoid 5-tuple collisions in cases where the destination happens to have an HTTP policy.
Do the same for east/west L7 LB (e.g., GAMMA) if the chosen destination is in the same node.
Same node destinations receive the source security identity via an skb_mark, so the original source address is not needed for policy enforcement at the destination.
=> bpf_metadata: Skip original source address for same node L7 LB destinations

cilium/bpf_metadata.cc, cilium/bpf_metadata.h, cilium/filter_state_cilium_policy.h, cilium/socket_option_source_address.cc, cilium/socket_option_source_address.h
We already skip using the original source address/port for non-L7 LB destinations in the same node. This is needed to avoid 5-tuple collisions in cases where the destination happens to have an HTTP policy.
Do the same for east/west L7 LB (e.g., GAMMA) if the chosen destination is in the same node.
Same node destinations receive the source security identity via an skb_mark, so the original source address is not needed for policy enforcement at the destination.
=> [v1.33] bpf_metadata: Skip original source address for same node L7 LB destinations

envoy_build_config/extensions_build_config.bzl
This commit enables the extension `envoy.rbac.principals.mtls_authenticated`.
=> extensions: enable RBAC mtls authenticated extension

.github/workflows/build-envoy-image-ci.yaml, .github/workflows/build-envoy-images-release.yaml, .github/workflows/ci-clang-tidy.yaml, .github/workflows/ci-tests.yaml, .github/workflows/codeql.yml
CNCF has hosted ephemeral GitHub runners on Oracle that we want projects to use instead of the GitHub-hosted ones, which now incur a cost to use.
Please direct any questions to me, @jeefy, @krook, and @RobertKielty. You can also join `#cncf-ci-infra` channel on CNCF Slack.
> [!NOTE]
Oracle Cloud has a feature called OCPU, which comes with 2 VCPUs by default. The VM `oracle-vm-32cpu-128gb-x86-64` we provide has effectively 64 cores, so the number of CPUs is the same (but the memory is half of what you use at the moment)
=> update github runners to oci gh arc runners

cilium/network_filter.cc
Historically, SNI was always propagated from downstream to upstream
in case of E/W Cilium policy enforcement.
But this should not be done in case of L7 loadbalancing, where the
upstream connection might have a completely different TLS configuration
where this SNI propagation (and validation) could potentially break
the upstream TLS handshake.
Therefore, this commit modifies the condition to only perform the
propagation if it's not L7LB.
Signed-off-by: Marco Hofstetter <marco.hofstetter@isovalent.com>
=> network_filter: don't propagate SNI in case of L7LB

.github/workflows/build-envoy-images-release.yaml
Fixes: b2011b733cac83caa6be869abd9ca61f37aaeaa2
--- 
The below failure was in main
```
Error: buildx failed with: ERROR: failed to build: failed to solve: failed to push quay.io/cilium/cilium-envoy-builder:main-archive-latest: unauthorized: access to the requested resource is not authorized
```
=> gha: Add login step for quay.io

cilium/api/npds.proto, cilium/network_policy.cc, cilium/network_policy.h, go/cilium/api/npds.pb.go, go/cilium/api/npds.pb.validate.go, proxylib/proxylib/policymap.go, tests/cilium_network_policy_test.cc
Add new 'precedence' field.
Fix handling of deny rules when looking to TLS context and proxylib reference.
Storage of rules for any given port range is flattened to a single sorted vector, which makes dealing with deny rules and precedence field much more straightforward. This restructuring is visible in the policy debug formatting.
=> policy: Support rule precedence

proxylib/proxylib/test_util.go
Maintaining the current behaviour in the test suite, this allows these fatal log calls to be overriden externally by fuzzers, as any exit call within a fuzzer is treated as an error by the CI.
See: https://github.com/cncf/cncf-fuzzing/pull/559 and https://github.com/cilium/cilium/pull/40728
=> tests: Wrap calls to logrus.Fatalf in a var

envoy_build_config/extensions_build_config.bzl
Fixes: https://github.com/cilium/proxy/issues/1513
New binary
```
$ docker run -it quay.io/cilium/cilium-envoy-dev:74bbfa06a13b1871a482392b7baad6702182e23c@sha256:e8d1d72e4c35f9270fe479d8b119b1ec1a6adb3a618f1651448dc526b0e10465 ls -lrth /usr/bin/cilium-envoy
-rwxr-xr-x 1 1337 1337 68M Aug  8 14:04 /usr/bin/cilium-envoy
```
Old binary from main branch
```
$ docker run -it quay.io/cilium/cilium-envoy:v1.35.0-1754542821-43b62ac18029bf5e22cbcc9e7141ee55eb09555d@sha256:2173f013b41e71cf8d65503cc9710c106746efbd93ae0ef3f46ee65de13b19f6 ls -lrth /usr/bin/cilium-envoy
-rwxr-xr-x 1 1337 1337 68M Aug  7 05:21 /usr/bin/cilium-envoy
```
=> extensions: Enable http3 related filters

.github/workflows/codeql.yml
As per the below release note, Envoy 1.35 no longer has the build config clang-libc++. This commit is to fix the build process in codeql workflow
```
Consolidated clang/gcc toolchains using --config=clang or --config=gcc.
```
Relates: https://github.com/envoyproxy/envoy/releases/tag/v1.35.0
=> gha: Fix build error due to clang-libc++

.github/renovate.json5, .github/workflows/ci-tests.yaml, .github/workflows/cilium-integration-tests.yaml
The goal is to have go upgrade done in one simple PR instead of 2 separate PRs as per below example.
- github action https://github.com/cilium/proxy/pull/1568
- others https://github.com/cilium/proxy/pull/1569
Fixes: 93d0d64e780465efe778011a9686ec578ce56e51
=> renovate: Correct package name in Go group
